== ¿Qué es la ley de Dios?

Para comprender la ley de Dios, conviene dar un paso atrás y comenzar con otra pregunta,
a saber: _¿qué es una ley?_
La primera definición que a menudo viene a la mente es simplemente una regla o mandamiento,
pero el significado de ley es más profundo que esto.
Es cierto que algunas leyes son solo reglas, pero también hay otras clases de leyes.
En la creación exterior existen leyes de la naturaleza, como las leyes del movimiento,
la gravedad o la termodinámica.
También existen leyes civiles, leyes de la ciencia y leyes de tránsito.
En las Escrituras leemos acerca de la Ley mosaica escrita,
pero también leemos acerca de una ley invisible de pecado y muerte, una ley de justicia,
una ley de libertad y la ley del Espíritu de vida
en Cristo Jesús. En Romanos capítulo siete,
Pablo habla de dos leyes diferentes y contrarias
obrando al mismo tiempo en su propia persona.

Al buscar una definición de ley que funcione en todos los casos, sugiero la siguiente:
_Una ley es un poder que gobierna._
En otras palabras, es _una regla o autoridad que nunca cambia,
y que exige conformidad u obediencia cuando actúa sobre algo más._ La ley de la gravedad,
por ejemplo,
es una regla o poder constante que nunca cambia y que exige obediencia
o conformidad siempre que actúa sobre un objeto en este mundo.
Una ley de tránsito también es una autoridad constante,
o un poder establecido por la legislación. No cambia
por las opiniones o preferencias del hombre,
y exige obediencia o conformidad cuando actúa sobre todos los conductores.
¿Y qué hay de la ley del pecado?
El pecado también es un poder o naturaleza constante que nunca cambia.
Siempre busca el yo, siempre obra el mal y las tinieblas, y cuando actúa sobre el hombre,
exige obediencia y conformidad mientras distorsiona la imagen y
semejanza de Dios en todo aquel que camina conforme a la carne.

La ley no comenzó con Moisés. La ley comenzó con Dios, y comenzó como algo santo,
justo y bueno.
Antes de la caída, la vida o naturaleza de Dios era la ley,
o el poder que gobernaba sobre todas las cosas creadas.
No me refiero a reglas o mandamientos escritos o pronunciados.
Quiero decir que la vida misma de Dios--quién era, cómo era, qué era; qué sabía, sentía,
veía y amaba;
Su misma naturaleza y ser manifestándose--era la regla o poder constante que nunca cambiaba,
y que actuaba sobre toda Su creación,
llevando todo a una conformidad viva con Él. Esta
no era una conformidad forzada a reglas exteriores,
o un código escrito de cumplimiento obligatorio.
Era una conformidad y unidad tanto interior como exterior; un poder vivo que,
al actuar sobre toda la creación,
producía un perfecto alineamiento y conformidad con su Creador.

En el principio,
todo en la creación vivía feliz y armoniosamente
en esta ley del amor y la bondad de Dios,
y por ella.
Cada cosa creada, animada o inanimada,
permanecía en su lugar y posición en la voluntad y poder de Dios.
No había nada contrario a Él, nada independiente de Él,
ni una sola cosa que se opusiera a Su naturaleza, vida o gobierno.
Por lo tanto, toda la creación permaneció por un tiempo en un _perfecto estado de gloria_.
La gloria es simplemente una manifestación visible del bien invisible de Dios;
y por un corto tiempo,
tanto el universo natural como el espiritual fueron ámbitos vivientes
que recibían felizmente y exhibían gloriosamente las maravillas,
perfecciones y atributos de Dios.
Todas las cosas guardaban natural y libremente esta perfecta ley de libertad.
Ese era su estado o morada creada.
Todas las cosas se sometían voluntariamente a Su gobierno,
y esta feliz sumisión era tanto el gozo de la criatura como la majestad del Creador.

Ahora bien,
había al menos dos tipos de seres que fueron creados para recibir y manifestar
una medida aún mayor de la gloria de Dios que el resto de la creación,
y estos dos seres eran humanos y ángeles.
A diferencia del resto de la creación natural,
se dice específicamente que los seres humanos fueron creados "`a imagen
y semejanza de Dios`". Y por el relato que se da de ellos en las Escrituras,
podemos suponer que los ángeles fueron creados con casi el mismo propósito y potencial.
Pero ambas criaturas, al recibir una mayor capacidad para la gloria,
también tenían una mayor libertad de volverse contra la perfecta ley de Dios.
Es decir, podían someterse a la ley de la vida, la voluntad y la naturaleza de Dios,
y conservar en ella su morada; o podían volverle la espalda y separarse de ella.

Esto es precisamente lo que sucedió. Algunos de los
"`ángeles que no guardaron su primer estado,
mas dejaron su propia habitación`";
y por esto fueron separados de la gloria de Dios y "`reservados debajo de oscuridad,
en cadenas eternas, hasta el juicio del gran día`".^
footnote:[Judas 1:6 RV1602 Purificada]
Estos fueron los primeros infractores de la ley, es decir,
las primeras criaturas en toda la creación que transgredieron
la santa ley de la perfecta voluntad y poder de Dios.
Se negaron a que Su inmutable naturaleza actuara sobre ellos.
Rechazaron la conformidad con Su verdad eterna.
Quebrantaron Su ley espiritual y rápidamente hallaron en
sí mismos el horrible fruto de su propia e insensata elección.
De gloriosos ángeles se convirtieron en miserables demonios.
Fueron expulsados de su habitación celestial y ahora vagan "`rodeando la tierra`"^
footnote:[Job 1:7]
con una naturaleza contraria y oscura "`buscando a quien devorar`".^
footnote:[1 Pedro 5:8]

Trágicamente, no pasó mucho tiempo antes de que la humanidad siguiera sus pasos.
El hombre era la corona de la creación natural,
la imagen y semejanza más clara del Dios invisible en el universo físico.
Pero él también usó el don de su voluntad--un don que lo capacitaba para buscar,
aferrarse,
amar y adorar el bien de su Creador--para apartarse
de Dios y perseguir los deseos de sus ojos terrenales,
los deseos de su carne y la vanidad de su vida.
De esta manera, él también transgredió la ley viva de Dios.
Se salió de su primer estado,
dejó su habitación celestial en la voluntad y naturaleza de Dios,
e inmediatamente trajo desorden,
deformidad y una maldición sobre toda la creación de abajo.

De repente, hubo _una ley nueva y diferente_ operando en la creación de Dios.
¿Qué era esta nueva ley?
Era "`la ley del pecado y de la muerte`",^
footnote:[Romanos 8:2]
una regla o poder nuevo e inmutable que exigía obediencia
y conformidad de todo aquello sobre lo que actuaba.

El pecado puede ser definido simplemente como contrariedad
o enemistad contra la ley o naturaleza perfecta de Dios.
Es la presencia y el poder de algo más en la creación de
Dios que vive y crece mediante una voluntad contraria.
Dios es el creador del universo, pero Él no es el creador del pecado.
El pecado no fue creado; nació cuando criaturas perfectas, en una creación perfecta,
apartaron su voluntad de la ley de la vida celestial para obrar en independencia,
es decir, desde _el yo._
Este es el origen del pecado, y sigue siendo su poder hasta el día de hoy.
Cada vez que una criatura usa los dones de Dios para apartarse de Dios hacia el yo,
se separa de la ley de la vida y entra en la ley del pecado,
donde la muerte espiritual se convierte en la consecuencia inevitable.
En el lenguaje de Pablo: "`La paga del pecado es muerte`".^
footnote:[Romanos 6:23]

El pecado es muy parecido a un cáncer que crece en un cuerpo sano.
La salud no crea el cáncer; no es parte del diseño de un cuerpo.
Pero cuando un trastorno persistente comienza a usar la vida,
las células y la energía de una persona para provocar
un crecimiento que es contrario al bien del cuerpo,
entonces ha nacido la enfermedad, y la muerte es muchas veces el resultado inevitable.
El pecado es un cáncer que apareció en la creación perfecta de Dios cuando la
voluntad de los ángeles y los hombres se volvió contra la ley de vida de Dios.
Y todo lo que vive en esta voluntad independiente, es decir,
todo lo que camina en la _voluntad del yo_, está bajo esta ley de pecado,
se convierte en un esclavo de ella,
y es conducido por ella por un camino que lleva a la destrucción.
Esta es la ley del pecado y de la muerte.

Aunque Israel era un territorio sometido al dominio romano durante el tiempo de Cristo,
los judíos se consideraban libres porque había pocas leyes
exteriores que restringieran su libertad para vivir,
trabajar y adorar a su Dios.
Jesús, sin embargo,
les dijo que había una ley mucho mayor que tenía jurisdicción sobre ellos,
y que cada acto de pecado era una prueba de su dominio.

[.embedded-content-document]
--

__Le respondieron: Linaje de Abraham somos, y jamás hemos sido esclavos de nadie.
¿Cómo dices tú: Seréis libres? Jesús les respondió: De cierto, de cierto os digo,
que todo aquel que hace pecado, esclavo es del pecado.__^
footnote:[Juan 8:33-34]

--

Mientras esta nueva ley del pecado y de la muerte fuera el principio que
gobernaba en los hombres--mientras fuera la inmutable regla que demandaba
conformidad y obediencia cuando actuaba sobre el corazón del hombre--no
había nada que pudiera hacerse para su salvación y felicidad.
En otras palabras, si los hombres vivían como esclavos del pecado,
necesariamente morirían en sus pecados, y no podrían volver a su condición original.
"`Otra vez les dijo Jesús: Yo me voy, y me buscaréis, pero en vuestro pecado moriréis;
a donde yo voy, vosotros no podéis venir`".^
footnote:[Juan 8:21]

El perdón por sí solo no es la solución a este problema.
El perdón del pecado es un don maravilloso y una
parte necesaria de la obra redentora de Dios.
Pero el perdón por sí mismo no mata este cáncer ni sana esta enfermedad
en la creación. La solución que el hombre necesitaba,
y la cosa misma que ofreció Jesucristo, fue un __"`camino nuevo y vivo`"^
footnote:[Hebreos 10:20]
para volver a entrar en la ley original de vida de
Dios y quedar nuevamente bajo su gobierno.__
Él necesitaba ser liberado de "`la ley del pecado y de la muerte`"
mediante "`la ley del Espíritu de vida en Cristo Jesús`".^
footnote:[Romanos 8:2]
Pero antes de que la vida y la inmortalidad fueran sacadas a luz por el evangelio,
se dio al pueblo de Dios una ley escrita de mandamientos justos,
siendo "`añadida a causa de las transgresiones`".^
footnote:[Gálatas 3:19]
