== Una ley escrita en tablas

En Gálatas 3:19 Pablo escribe: "`¿Para qué entonces, sirve la ley?
Fue añadida por causa de las transgresiones,
hasta que viniese la simiente a quien fue hecha la promesa`".
¿Cuál es la ley a la que Pablo se refiere aquí? ¿Y qué significa
que fue añadida por causa de la transgresión? Evidentemente,
no se trata de una ley de vida interior y espiritual,
ni una regla en la creación física como la ley de la gravedad.
Aquí, la ley que Pablo tenía en mente era la ley de Moisés;
una regla exterior y escrita que requería conformidad u obediencia de
parte del pueblo que había sido introducido en un pacto con Dios.

En un sentido se podría decir que la ley escrita de Moisés
era como una ley de tránsito o una ley civil,
en que sus exigencias eran impuestas sobre los hombres desde fuera, y no desde dentro.
Y "`fue añadida por causa de las transgresiones`" porque la humanidad
había dejado de vivir conforme a la ley de vida^
footnote:[También llamada la "`ley de la fe`" o la "`ley de Cristo`" en el Nuevo Testamento.
Ver Romanos 3:27; 8:2; Gálatas 6:2; 1 Corintios 9:21]
o naturaleza de Dios.
Es decir, debido a que el hombre se había apartado de la justicia de Dios en su interior,
y no se sometía interiormente a la justicia que venía de Dios,^
footnote:[Ver Romanos 10:3]
entonces Dios añadió o impuso una ley escrita de requisitos para gobernarlo desde fuera,
hasta que el nacimiento y crecimiento de la Simiente de
Dios en el hombre restaurara la naturaleza que había perdido.

Abel, Noé y Abraham fueron hombres que caminaron por fe, y al menos, en algún grado,
recibieron y participaron de la justicia de su Creador.
Mucho antes de que hubiera una ley exterior escrita en tablas y pergaminos,
Abel "`obtuvo testimonio de que era justo`",^
footnote:[Hebreos 11:4 RV1602P]
"`Noé halló gracia ante los ojos de Jehová`",^
footnote:[Génesis 6:8]
"`Creyó Abraham a Dios, y le fue contado por justicia`".^
footnote:[Romanos 4:3]

Pero cuando llamó a Israel a salir de su esclavitud en Egipto,
halló que era un pueblo rebelde y de dura cerviz,
que continuamente murmuraba contra Su guía y "`siempre andaban vagando en su corazón`".^
footnote:[Hebreos 3:10]
Por causa de la continua rebelión interior y las transgresiones exteriores,
los puso bajo una ley escrita que entregó a Moisés en el monte Sinaí. Este no
era un sistema de reglas y regulaciones arbitrarias para probar su obediencia,
o para satisfacer la justicia de Dios con ritos y ceremonias.
Muy por el contrario, la ley mosaica era una descripción exterior,
una representación física o un espejo de la ley viva de justicia
que Adán y Eva habían abandonado y perdido en el principio.
Como testifican las Escrituras,
la ley escrita tenía "`la forma del conocimiento y de la verdad`",^
footnote:[Romanos 2:20 RVG]
y "`la sombra de los bienes venideros`", pero "`no la imagen misma de las cosas`".^
footnote:[Hebreos 10:1]
Es decir,
la ley era la forma y descripción externas de una naturaleza e
imagen internas que el hombre no podía generar por sí mismo.

Es de suma importancia que comprendamos que esta ley escrita de justicia no era
en absoluto _contraria_ a la ley de vida que una vez reinó en el alma del hombre.
Hago hincapié en este punto porque es común oír a
cristianos hablar de la ley de manera despectiva,
o presentarla como enemiga del evangelio.
Pero la ley escrita dada a través de Moisés no puede
ser considerada en ninguna forma mala o equivocada.
Muy al contrario, Pablo nos dice que era "`santa, justa y buena`".^
footnote:[Romanos 7:12]
El único problema con la ley era que se trataba de
una descripción y un requisito exterior de justicia,
y no de una naturaleza o vida interior de justicia.
Y esto, en verdad, creó dificultades para los hijos caídos de Adán.

En otras palabras,
la razón por la cual las Escrituras a veces hablan de la ley mosaica de manera desfavorable
es porque efectivamente había algo desfavorable en _la relación del hombre con la ley_.
El problema no era la ley misma,
sino el hecho de que una ley exterior y escrita de mandamientos no podía
cambiar ni vencer la ley interior del pecado y de la muerte que reinaba
en el hombre caído. No era más que palabras escritas en una piedra,
y no una naturaleza escrita en el corazón. Era una descripción y un requisito de justicia,
y no una vida de justicia.
Y debido a que solo eran palabras que describían
una naturaleza que el hombre había perdido,
lo más que podía hacer era manifestar y reprender (de múltiples maneras) el mal,
la impureza y la enemistad que el hombre había introducido en sí
mismo al hacerse esclavo de la ley del pecado y de la muerte.

Una vez más,
la ley escrita de Dios no tenía en sí misma absolutamente nada malo ni equivocado.
Aunque las Escrituras hablan de nuestra liberación de la "`maldición`"^
footnote:[Gálatas 3:13]
de la ley, del "`yugo`"^
footnote:[Hechos 15:10]
de la ley, y de la "`condenación`"^
footnote:[2 Corintios 3:9]
de la ley,
estas expresiones no se usan porque la ley misma fuera defectuosa o perjudicial.
Más bien, porque la _carne_ es defectuosa y el _pecado_ es perjudicial,
y porque la ley escrita no podía hacer más que poner al descubierto
y condenar la raíz del pecado y sus frutos en el hombre.

Pablo corrige precisamente este malentendido en varios pasajes de sus cartas.
Por ejemplo:

[.embedded-content-document]
--

[.offset]
__Romanos 7:7 ¿Qué diremos entonces?
¿Es pecado la ley?
¡En ninguna manera!
Al contrario, yo no hubiera conocido el pecado a no ser por la ley.__

[.offset]
__Gálatas 3:21 ¿Luego la ley es contraria a las promesas de Dios?
¡En ninguna manera!__

[.offset]
__Romanos 7:12-13 De manera que la ley a la verdad es santa, y el mandamiento es santo,
y justo, y bueno.
¿Entonces lo que es bueno, vino a ser muerte para mí? ¡En ninguna manera!
Pero el pecado, para mostrarse pecado, obró muerte en mí por lo que es bueno,
a fin de que por el mandamiento, el pecado llegase a ser sobremanera pecaminoso.__

--

La ley escrita no era defectuosa; solo era _débil,_ y por esta razón:
porque no podía poner fin a la ley del pecado y de la muerte en el hombre.
En Romanos 8:3, Pablo dice que la ley "`era débil por la carne`". Es decir, por un lado,
que la carne no podía cumplir la justicia descrita por la ley; y por otro,
que una ley escrita no podía cambiar la naturaleza de la carne.
En Hebreos leemos que el mandamiento externo fue
"`abrogado a causa de su debilidad e ineficacia,
pues nada perfeccionó la ley`".^
footnote:[Hebreos 7:18-19]
El autor no dice que la ley fuera inútil o inservible,
sino solamente débil e ineficaz porque no podía perfeccionar nada.
En otras palabras, la ley escrita no podía remediar el problema del hombre.
Era demasiado débil para detener la inercia de una
ley más fuerte que ya estaba operando en su interior.

Imagina que hay un árbol enorme en mi patio que comienza
a balancearse peligrosamente durante una violenta tormenta,
como si fuera a caer sobre mi casa.
Al ver el peligro, entro corriendo en la casa,
llamo al presidente de los Estados Unidos y le pido
que promulgue una nueva ley que declare:
"`De ahora en adelante,
queda prohibido que cualquier árbol caiga sobre la casa
de Jason Henderson`". El presidente acepta mi propuesta,
respalda la ley,
obtiene la aprobación del congreso y de inmediato
me envía por correo electrónico una copia oficial.
Después de imprimirla, corro de nuevo hacia el árbol tambaleante,
leo la ley en voz alta y pienso para mis adentros: "`¡Uf, por poco!`"
Pero al cabo de unos pocos minutos,
el viento cobra fuerza de nuevo y el árbol--sin inmutarse
ante mi buena y justa ley--se parte con un fuerte crujido,
cae violentamente y aplasta mi casa.

Esta es una analogía tonta, pero sin duda puedes ver el punto:
_la ley de la gravedad es más fuerte que una ley escrita que prohíbe a la gravedad actuar._
Mi ley era buena y justa, pero era "`débil`" a causa de la gravedad,
e "`ineficaz`" porque no pudo salvar mi casa.

La ley escrita era solo una sombra exterior de la ley de vida, es decir,
de la regla interior que Dios quería restaurar en el hombre.
Era una buena _descripción_ de la justicia, pero no era la _vida_ de justicia.
Manifestaba las cosas malas y señalaba las mejores,
pero ni en sí misma ni por sí misma tenía poder para _impartir_ lo que describía.
Y esto es precisamente lo que Pablo nos dice en su carta a los Gálatas.

[.embedded-content-document]
--

__¿Es entonces la Ley contraria a las promesas de Dios?
¡De ningún modo!
Porque si se hubiera dado una ley [.underline]#capaz de impartir vida,#
entonces la justicia ciertamente hubiera dependido de la ley.__^
footnote:[Gálatas 3:21 LBLA]

--

La justicia habría sido alcanzada por la ley escrita
si esta hubiera podido impartir la vida de Dios.
Pero, al no ser el caso, el hombre necesitaba algo más fuerte.

Por lo tanto, al ver que el hombre había perdido la "`ley de vida`" interior,
y quedado bajo la "`ley del pecado y de la muerte`",
el Dios de sabiduría y misericordia--con miras a la redención del
hombre--dio a Israel una ley escrita de mandamientos y ordenanzas,
estableciéndola sobre Su pueblo como una luz y un estándar de justicia.
Esto lo hizo por al menos las siguientes tres razones:

[.numbered-group]
====

[.numbered]
_Primero:_
para que la descripción y el requisito de justicia en la ley escrita pusieran al descubierto,
señalaran y condenaran la ley del pecado que operaba en el corazón del hombre.
Esto está claramente declarado en multitud de Escrituras.^
footnote:[Ver Romanos 3:20, 4:15, 5:13, 5:20, 7:5, 7:7-11, 7:13; 2 Corinthians 3:7-9;
Galatians 3:19, 3:22]

[.numbered]
_Segundo:_ para que, mediante el establecimiento de reglas y normas de justicia,
ordenanzas y ceremonias de adoración, preceptos para lo puro y lo impuro,
la carne y el Espíritu, etc.,
Dios pudiera evitar que los portadores de Su testimonio se hundieran aún más
en la degradación y corrupción que se había extendido en las naciones circundantes.^
footnote:[Éxodo 19:15-16; Levítico 18:3-5, 24-30; Deuteronomio 19:9-14]

[.numbered]
_Tercero:_ para que por estas dos primeras cosas--es decir,
tanto la manifestación de la naturaleza de pecado, como las varias reglas, ordenanzas,
ceremonias,
tipos y sombras de la ley--Dios pudiera dirigir el
corazón del hombre hacia la Simiente de vida,
el nacimiento de la naturaleza celestial de Cristo,
que podría traer de regreso al hombre bajo la ley de vida que había perdido en la caída.

====

Y cuando hablo de la ley externa dirigiendo el corazón del hombre hacia Cristo,
la Simiente, no me refiero solamente a Su venida exterior como Hombre en Israel.
Hay, en efecto,
muchas figuras y tipos en la ley mosaica que ilustran la obra de
Cristo en el cuerpo como el Hijo del Hombre y el Cordero de Dios.
Pero la mayor parte de los mandamientos,
ceremonias y sombras en la ley ilustran la necesidad
que tiene el hombre de un Salvador interior,
uno que mate la naturaleza bestial interior, limpie el interior del vaso,
sane la lepra del corazón y haga que un pueblo sea interiormente
apto para adorar al Señor en la hermosura de la santidad.
