== Libertad de la Ley

Consideremos ahora la primera razón antes mencionada por la cual se añadió la ley,
a saber:
para que una descripción y un requisito de justicia expusieran
y condenaran la ley del pecado que reina en el corazón del hombre.
Es importante que lleguemos a una comprensión clara
de la relación entre la ley y la carne,
y también que no intentemos escapar de esta importante obra de la ley
sin escapar de la naturaleza de la carne que es condenada por ella.

En un sentido se podría decir que la ley escrita, con todas sus reglas,
requisitos y advertencias, señalaba con su dedo multitud de malas acciones,
comportamientos, pensamientos y deseos, y de diversas maneras decía:
"`¡Aquí hay algo que es contrario a la naturaleza y a la justicia de Dios!`"
Señalaba lo inmundo, la perversión, la injusticia, el egoísmo,
el orgullo de todo tipo y decía: "`¡Eso es contrario a la ley de vida de Dios!`"
Iluminaba con una linterna toda infección y enfermedad en la condición humana, y decía:
"`¡He encontrado un trastorno! ¡He hallado algo equivocado, algo peligroso!`"
Esta es la naturaleza de la relación entre el requisito justo de
Dios y la naturaleza de pecado que reina en la carne.
Y es una relación _permanente_ y _inalterable_,
porque una es una descripción y un requisito de la justicia de Dios,
y la otra es una desviación de la justicia y una contradicción de ella.

Esta es la razón por la que Pablo, en 2 Corintios 3:9,
se refiere a la ley como un "`ministerio de condenación`".
Era un ministerio de condenación porque,
al ministrar el conocimiento de la justicia de Dios,
no podía evitar condenar todo lo que era contrario a ella.
En Romanos, Pablo dice: "`Por medio de la ley es el conocimiento del pecado`".^
footnote:[Romanos 3:20]
Y, "`La ley se introdujo para que el pecado abundase`".^
footnote:[Romanos 5:20]
Y, "`¿Qué diremos, pues?
¿La ley es pecado?
En ninguna manera.
Pero yo no conocí el pecado sino por la ley`".^
footnote:[Romanos 7:7]

Ahora bien,
es probable que muchos estén familiarizados con estos versículos y conceptos
en relación con la función de la ley en el antiguo pacto de Israel.
Sin embargo,
lo que a menudo se pasa por alto es que la incompatible relación
entre el justo requisito de Dios y la naturaleza pecaminosa del
hombre no desapareció cuando Jesús resucitó de entre los muertos,
ni cambia cuando una persona llega a la fe en Cristo.
De ninguna manera sugiero que los cristianos aún están bajo los símbolos, ceremonias,
reglas y castigos externos de la teocracia del antiguo pacto.
Sin embargo, la naturaleza justa descrita y requerida por la ley,
y la necesidad de ser santo como nuestro Padre celestial es santo,
no ha cambiado en lo absoluto; ni tampoco la perspectiva de Dios sobre el pecado.
La verdad es que la enemistad entre el pecado y la justicia no puede cambiar.
"`¿Qué compañerismo tiene la justicia con la injusticia?
¿Y qué comunión la luz con las tinieblas?`"^
footnote:[2 Corintios 6:14]
Por definición y por su propia esencia,
estas dos naturalezas son eternamente contrarias entre sí. La milagrosa encarnación,
vida, muerte y resurrección del Señor Jesucristo, y el derramamiento de Su Espíritu,
llevaron a cabo una obra que sobrepasa toda comprensión humana;
pero no reconciliaron a Dios con el pecado,
ni de ninguna manera eliminaron la enemistad entre estas dos naturalezas contrarias.
Aquí es donde suele surgir la confusión.

Hoy en día es común que los cristianos piensen que no tienen nada
que ver con el "`ministerio de condenación`" de la ley,
simplemente porque son creyentes en Jesús, o porque nacieron después de la muerte,
sepultura y resurrección de Cristo.
No es inusual oír afirmaciones como:
"`La condenación por el pecado era parte del antiguo pacto`",
o "`me alegra vivir en el tiempo del nuevo pacto,
en el que soy libre de la ley`". Pero afirmaciones
como estas a menudo demuestran grandes malentendidos.

Es absolutamente cierto que Dios ha hecho un nuevo pacto
con el hombre a través de la sangre de Jesucristo,
y que este pacto no se aprende como reglas y preceptos escritos sobre piedra,
ni se guarda como ceremonias,
rituales y otros tipos y figuras externas de realidades espirituales.
El nuevo pacto es una relación con Dios en el Espíritu vencedor de Su Hijo,
un Espíritu que fue derramado,
o puesto a disposición de toda carne cuando Cristo venció todo obstáculo para
la redención del hombre y abrió un camino nuevo y vivo para acercarse a Dios.
En este nuevo pacto, el hombre puede nacer del Espíritu, vivir por el Espíritu,
andar en el Espíritu, y experimentar la "`ley del Espíritu de vida en Cristo Jesús`"^
footnote:[Romanos 8:2]
cumpliendo en nosotros los requisitos justos de la ley.
Por medio de Él, el hombre puede ser regenerado, santificado,
lavado y transformado a la imagen de su Salvador.
Se podría decir mucho más sobre el increíble don del Espíritu de
Cristo y del pacto establecido con el hombre en Él. Pero si,
después de creer en Cristo y recibir Su Espíritu continuamos
andando en la carne--o tal vez sea mejor decir que,
en cualquier medida que continuemos viviendo en la carne después
de haber sido hechos partícipes de Su Espíritu--la ley justa de
Dios todavía va a señalar con su dedo toda forma de pecado,
egoísmo y corrupción, y decir:
"`¡Aquí hay algo que es contrario a la naturaleza de Dios! ¡Aquí hay algo malo,
algo peligroso, algo que debe morir para que puedas ser libre!`"

Los cristianos con frecuencia objetan tal idea,
argumentando que la gracia ha quitado la necesidad de que el pecado sea expuesto y juzgado^
footnote:[No debe confundirse el juicio con el castigo.
El juicio tiene que ver con una separación o distinción entre dos cosas contrarias.
El Dios de amor trae juicio en Su luz para que podamos
reconocer nuestra condición y seguirle fuera de ella.
Esto hizo que David dijera: "`Los juicios de Jehová son verdad; todos justos.
Deseables son más que el oro, y más que mucho oro afinado; y dulces más que miel,
y que la que destila del panal`" (Salmo 19:9-10).]
en los creyentes.
La gracia es, en efecto, maravillosa, y en breve hablaré mucho de ella,
pero algo que la gracia no hace es cambiar el justo estándar de Dios,
ni forjar una comunión entre el pecado y la justicia.
El pecado sigue siendo pecado,
ya sea que hayas nacido en los días de Moisés o dos mil años después de Pentecostés.
Y el justo estándar de Dios que manifiesta el pecado tiene derecho a continuar su obra,
hasta que sus justos requisitos sean cumplidos por
la vida de Su Hijo reinando en el hombre.
En otras palabras,
el dedo justo de Dios va a continuar señalando todas
las cosas en Su creación que son contrarias a Él,
hasta que todas hayan sido gozosamente restauradas bajo la ley original de Su vida,
naturaleza y Espíritu.
Pero dondequiera que el hombre continúe viviendo en la carne,
allí la ley todavía tiene autoridad para exponer y condenar.

Esto es precisamente lo que Pablo dice en los primeros
seis versículos del capítulo siete de Romanos.

¿Acaso ignoráis, hermanos (pues hablo con los que conocen la ley),
que la ley se enseñorea del hombre entre tanto que este vive?
Porque la mujer casada está sujeta por la ley al marido mientras este vive;
pero si el marido muere, ella queda libre de la ley del marido.
Así que, si en vida del marido se uniere a otro varón, será llamada adúltera;
pero si su marido muriere, es libre de esa ley,
de tal manera que si se uniere a otro marido, no será adúltera.
Así también vosotros, hermanos míos, habéis muerto a la ley mediante el cuerpo de Cristo,
para que seáis de otro, del que resucitó de los muertos,
a fin de que llevemos fruto para Dios.
Porque mientras estábamos en la carne,
las pasiones pecaminosas que eran por la ley obraban
en nuestros miembros llevando fruto para muerte.
Pero ahora estamos libres de la ley,
por haber muerto para aquella en que estábamos sujetos,
de modo que sirvamos bajo el régimen nuevo del Espíritu
y no bajo el régimen viejo de la letra.

Pablo comienza afirmando que la ley se enseñorea, o tiene jurisdicción,^
footnote:[Como lo tiene LBLA]
sobre un hombre en tanto este vive.
Esta es una declaración significativa.
En tanto el hombre continúe viviendo su propia vida--la vida de la carne,
o del primer nacimiento--la ley conserva su señorío,
o su derecho a condenar esa naturaleza transgresora.
Recordemos que existe una relación fija e inalterable
entre la ley justa de Dios y la carne pecaminosa.
No puede terminar porque Dios no puede cambiar.
Por esta razón Pablo compara esta relación con la relación permanente
establecida entre un hombre y una mujer en el matrimonio.
Así como bajo la ley una mujer no podía jamás romper
o dejar de lado su relación con su marido,
así también,
una persona que está viviendo en la carne no puede
invalidar ni liberarse de la condenación de la ley,
porque la ley tiene pleno derecho de condenar esa naturaleza.
La ley tiene jurisdicción sobre la naturaleza de la carne dondequiera que viva,
y la carne está legítimamente bajo su autoridad.

Ahora, en esta relación de matrimonio entre la ley y la carne, la ley no puede morir.
Dicho de otra manera, el justo requisito de Dios no puede cambiar ni dejar de ser.
No obstante, la naturaleza pecaminosa de la carne sí puede morir.
Puede ser crucificada por la cruz de Cristo (el poder de Dios),
y de este modo el alma puede llegar a ser libre tanto
de la carne como de la condenación asociada a ella.
Esto es precisamente lo que Pablo declara en los siguientes versículos.
Mientras vivíamos en la carne,
dice "`las pasiones pecaminosas que eran por la ley obraban
en nuestros miembros llevando fruto para muerte.
Pero ahora estamos libres de la ley...`" Y, ¿cómo dice que somos liberados de la ley?
"`...por haber muerto para aquella en que estábamos sujetos,
de modo que sirvamos bajo el régimen nuevo del Espíritu
y no bajo el régimen viejo de la letra`".^
footnote:[Romanos 7:5-6]
¿Pueden ver lo que está diciendo Pablo?
Mientras el alma del hombre vive en la naturaleza pecaminosa de la carne y bajo su dominio,
está necesariamente atada a la condenación de la ley.
Pero cuando ella muere a la carne, la ley pierde el objeto de su condenación,
porque la ley solo fue añadida para restringir y juzgar a la naturaleza transgresora.
Así, pues, al morir a la carne por medio de la cruz de Cristo,
el alma puede ser unida a Otro y llevar fruto justo para Dios.

Aquí está el punto principal:
la manera de ser libre de la condenación que corresponde a la naturaleza pecaminosa
de la carne es muriendo a la carne por medio de la cruz de Cristo.
No es por nacer en el siglo XXI, después del tiempo del antiguo pacto.
No es por asistir a la iglesia, ni simplemente por creer en la venida,
muerte y resurrección externas de Cristo.
La libertad de la condenación de la ley es por "`haber muerto para aquella en que estábamos
sujetos`". Es por medio de una participación personal en la muerte de Cristo,
la experiencia de la crucifixión de la naturaleza que es
(y siempre debe ser) condenada por la justa ley de Dios.
Y cuando "`la carne con sus pasiones y deseos`"^
footnote:[Gálatas 5:24]
es quitada, entonces la ley no tiene nada que condenar y la muerte ha perdido su aguijón.^
footnote:[1 Corintios 15:56, "`El aguijón de la muerte es el pecado,
y el poder del pecado, la ley`". Lo cual, según entiendo, quiere decir:
Lo que hace que la muerte tenga aguijón es la presencia o el predominio del pecado;
y lo que da al pecado el poder para aguijonear, o herir al hombre,
es la ley justa que nunca podrá estar en paz con él.]

Una de las razones por la que esto es tan importante es la peligrosa
inclinación del corazón del hombre a reclamar la libertad de la
ley sin experimentar libertad de la naturaleza que la ley condena.
Queremos decir que la ley pertenecía a otro tiempo y a otro contexto,
y que ahora no tiene verdadera importancia.
Queremos decir que la venida histórica de Cristo hace 2000
años acabó con los requisitos justos de Dios,
y que ahora no nos incumben.
Pero la verdad es que "`la ley se enseñorea del hombre
entre tanto que éste vive`" en la carne.
De nuevo, Pablo no quiere decir que las ceremonias y símbolos de la ley,
que eran sombras, deban continuar siendo guardados por los creyentes del nuevo pacto.
Él fue, quizás, el primero de los apóstoles en ver la Sustancia a través de los símbolos.
Solo quiere decir que la ley sigue siendo una "`santa, justa y buena`"^
footnote:[Romanos 7:12]
descripción y requisito de la justicia de Dios, y por tanto,
dondequiera o cuandoquiera que encuentre a un hombre
viviendo en una naturaleza contraria--es decir,
viviendo en la naturaleza caída de Adán--tiene todo
el derecho de exponer y condenar el pecado.

Y esta es la razón por la que Pablo afirma en el siguiente capítulo: "`Ahora, pues,
ninguna condenación hay para los que están en Cristo Jesús,
los que no andan conforme a la carne, sino conforme al Espíritu`".^
footnote:[Romanos 8:1 Aunque es cierto que la segunda mitad de
este versículo está ausente en unos pocos manuscritos griegos antiguos,
también es cierto que se encuentra en la inmensa mayoría de ellos (más de mil),
y no hace más que expresar lo mismo que se repite a lo largo de Romanos 8:1-17:
que los _creyentes_ deben escapar de la enemistad y de la muerte andando en el Espíritu.]
Y: "`Para que la justicia de la ley se cumpliese en nosotros,
que no andamos conforme a la carne, sino conforme al Espíritu`".^
footnote:[Romanos 8:4]
Y luego, escribiendo a aquellos que él llama "`hermanos`", es decir,
aquellos que ya eran creyentes en Cristo dice: "`Así que, hermanos, deudores somos,
no a la carne, para que vivamos conforme a la carne; porque si vivís conforme a la carne,
moriréis; mas si por el Espíritu hacéis morir las obras de la carne,
viviréis. Porque todos los que son guiados por el Espíritu de Dios,
éstos son hijos de Dios`".^
footnote:[Romanos 8:12-14]

Aquí vemos claramente que es posible "`vivir conforme a
la carne`" incluso después de recibir el don del Espíritu,
y que ni la venida exterior de Cristo, ni creer en Su nombre,
cambia la naturaleza de la carne,
o las consecuencias que recaen sobre aquellos que continúan andando en ella.
Si nosotros, dice Pablo, incluso como creyentes, continuamos andando en la carne,
moriremos.
Pero si, por vivir en y bajo el poder del Espíritu, hacemos morir las obras de la carne,
viviremos, y así seremos completamente libres de la condenación de la ley.

Sin embargo,
no podemos decir que no tenemos nada que ver con los requisitos justos de la ley hasta
que no tengamos nada que ver con la naturaleza que es condenada por la ley.
Es decir,
no podemos afirmar que estamos muertos a la ley hasta que estemos
muertos a la carne que es expuesta y reprobada por la ley.
En consecuencia, si todavía estamos viviendo en la carne--hallando nuestra vida,
corazón y hogar en el primer nacimiento caído--entonces
todavía estamos "`casados`" con la ley y su condenación,
y la ley mantiene su jurisdicción sobre nosotros.
Y si, en esta condición, también decimos que amamos a Cristo,
y que estamos casados con Cristo,
entonces creo que puede decirse con seguridad que está ocurriendo cierta medida de adulterio.
Porque "`ninguno puede servir a dos señores; porque o aborrecerá al uno, y amará al otro;
o estimará al uno y menospreciará al otro`".^
footnote:[Mateo 6:24]

Es común entre los cristianos oír y cantar que Cristo nos ha hecho libres,
y ciertamente hay una verdad maravillosa en esta declaración.
Pero asegurémonos de comprender qué es esta libertad,
y también cuándo,
cómo y si se aplica a nuestra presente condición. Aquellos que
afirman que Cristo nos ha hecho libres de la ley para que podamos
vivir nuestras propias vidas sin temor a la condenación,
están muy lejos de comprender el testimonio de las
Escrituras o el propósito de la venida de Cristo.
Cristo no nos ha hecho libres de la ley para que podamos vivir nuestras propias vidas;
Él nos ha hecho libres de nuestras vidas para que podamos vivir en Su Espíritu.
O--tomando prestado el lenguaje de Pablo--habiendo estado antes "`sujetos`" a la carne,
y mantenidos bajo el dominio de Satanás,
hemos sido "`libertados del pecado`" para que podamos llegar a ser "`siervos de la justicia`".^
footnote:[Romanos 6:18]

Es por esta razón que Jesús dice: "`De cierto, de cierto os digo:
Todo aquel que hace pecado, esclavo es del pecado.
Y el esclavo no queda en la casa para siempre; el Hijo sí permanece para siempre.
Así que, si el Hijo os libertare, seréis verdaderamente libres`".^
footnote:[Juan 8:34-36]
¿Libres de qué? Sus palabras no podrían ser más claras.
Jesús nos ofrece libertad de la esclavitud al pecado, y por consiguiente,
de la condenación de la ley.

Por lo tanto,
la verdadera libertad del nuevo pacto no consiste simplemente en prescindir de los rituales,
las reglas y las penalidades por actos de rebelión del antiguo pacto.
La libertad que Cristo ofrece es del yo y del pecado,
y es experimentada en nuestra sumisión a Su Espíritu vencedor.
Pablo dice: "`Donde está el Espíritu del Señor, allí hay libertad`".^
footnote:[2 Corintios 3:17]
Esta es una verdad maravillosa.
Pero por la misma regla,
donde no está el Espíritu del Señor--o donde todavía no está dirigiendo
y gobernando--allí el hombre permanece en sus cadenas.

Todo esto es claramente afirmado por Cristo mismo en el famoso Sermón del Monte,
donde dice:

No penséis que he venido para abrogar la ley o los profetas; no he venido para abrogar,
sino para cumplir.
Porque de cierto os digo que hasta que pasen el cielo y la tierra,
ni una jota ni una tilde pasará de la ley, hasta que todo sea cumplido.
De manera que cualquiera que quebrantare uno de estos mandamientos muy pequeños,
y así enseñare a los hombres, muy pequeño será llamado en el reino de los cielos;
mas cualquiera que los hiciere y enseñare,
éste será llamado grande en el reino de los cielos.
Porque os digo que si vuestra justicia no fuere mayor que la de los escribas y fariseos,
no entraréis en el reino de los cielos.^
footnote:[Mateo 5:17-20]

Aquí Jesús nos dice que la ley no puede ser destruida ni abolida,
porque (como ya hemos señalado) es la descripción escrita, o forma externa,
del bien y la justicia celestiales.
Es la naturaleza de Dios descrita con palabras y exigida al hombre por Dios mismo.
¿Cómo podría cambiar?
Cada jota y cada tilde de la ley escrita ilustra, manifiesta o exige algo que es santo,
justo y bueno.
Detrás de cada regla, ritual y lavamiento está este sencillo mensaje:
"`Si quieres ser Mío, debes ser como Yo; debes ser santo,
porque Yo el Señor tu Dios soy santo`". ¿Cómo podría Cristo destruir esto?
¿Por qué Cristo aboliría esto?
¿Cambió Dios Su mente en el nuevo pacto acerca de lo que es justicia?
¿O cambió Dios Su naturaleza y no la exige más? No, nada de eso.
¡Cristo no vino para abolir la ley, sino para _cumplirla_!

Pero, ¿qué significa que Cristo cumple la ley?
Primero que todo,
significa mucho más que el hecho de que Él guardó la ley de Dios sin fallar.
Jesús ciertamente "`nació de una mujer`" y "`nació bajo la ley`",^
footnote:[Gálatas 4:4]
como testifica Pablo.
Vivió una vida inocente y sin pecado,
y aunque fue acusado de quebrantar las tradiciones e interpretaciones
de las sectas religiosas de Su día,
guardó y honró la Ley de Moisés en cada detalle.
Pero satisfacer la ley y cumplir la ley no son lo mismo.

El cumplimiento tiene que ver con la llegada de aquello que fue testificado.
La ley describía, exigía y señalaba algo,
y ese _algo_ era la propia vida de Dios--Su naturaleza, justicia, amor, luz y Espíritu.
El objetivo de la ley era Cristo mismo, porque Cristo es la Persona,
la presencia y la perfecta realización de todo lo que las
reglas y símbolos del antiguo pacto habían descrito.
El cumplimiento no consiste simplemente en obedecer la ley, ni tampoco en destruirla,
quitarla o cambiarla.
Cumplimiento significa que cada jota y cada tilde de la ley llega
a su realidad y consumación en la _llegada de la Sustancia_.
La vida y la naturaleza de Jesucristo en el hombre es la sustancia viva
de todo lo que la ley describía. Recuerden Gálatas 3:19 y 24:
"`¿Para qué sirve la ley?
Fue añadida a causa de las transgresiones,
_hasta que viniese la simiente_ a quien fue hecha la
promesa... De manera que la ley ha sido nuestro ayo,
para llevarnos a Cristo`"

En pocas palabras,
el cumplimiento de la ley por parte de Cristo significa que el propósito de Su venida,
vida,
muerte y resurrección fue introducir y establecer
(primero en Él mismo como el Hijo del Hombre,
y luego en Su cuerpo,
la iglesia) la misma naturaleza justa que la ley describía mediante palabras y rituales.^
footnote:[Jeremías 23:6 "`En sus días será salvo Judá, e Israel habitará confiado;
y éste será su nombre con el cual le llamarán: Jehová, justicia nuestra`".]
Significa que la propia vida de Cristo puede ser hecha para nosotros "`sabiduría,
justificación, santificación y redención`".^
footnote:[1 Corintios 1:30]
Jesús no vino porque Dios cambiara lo que tenía en mente;
vino como el cumplimiento y la experiencia de lo que Dios siempre tuvo en mente.
Esto es lo que significa cumplir la ley.

La siguiente es una analogía un tanto absurda, pero tal vez ayude a ilustrar este punto.
Imaginen que un joven tenía una imagen muy clara
en su mente de la mujer con la que deseaba casarse.
Y, puesto que estaba muy seguro de lo que quería,
llenó un cuaderno con toda clase de descripciones y bocetos
de exactamente quién sería ella y cómo sería,
y luego comenzó a esperarla pacientemente.
En el curso de pocos años,
varias mujeres le fueron presentadas como posibles candidatas para el matrimonio,
pero después de sacar su cuaderno y hacer cuidadosas
comparaciones con todo lo que él había escrito,
descartó a cada una de ellas por no estar a la altura de sus expectativas.
Pero finalmente, después de esperar años, encontró a la joven de sus sueños,
se casó con ella y descubrió con mucha alegría que ella era, en efecto,
el cumplimiento vivo de todo lo que él había imaginado y registrado en su cuaderno.

Ahora les pregunto:
¿Acaso la llegada de esta joven cambió de alguna manera lo que él tenía en mente?
¿Contradijo, desestimó o abolió lo que él había escrito en su cuaderno?
Por supuesto que no.
No reemplazó sus expectativas, las satisfizo.
No cambió su descripción, la _cumplió_. Ella fue la llegada de la sustancia,
la perfecta realización de cada jota y tilde que él había escrito en su cuaderno.

De esta manera Jesucristo es el cumplimiento, la realización y la satisfacción de la ley.
Él no la cambió ni la abolió. Vino como aquello que la ley describía con cada palabra.
Por ejemplo, Jesús mismo era el aroma fragante mencionado en la ley que agradaba al Padre.
Era el agua purificadora que limpiaba al leproso,
la luz que brillaba desde el candelabro, el pan que caía del cielo,
y el fuego que consumía la carne en el altar.
Jesucristo era la naturaleza misma expresada en la ley moral:
la justicia en sus mandamientos civiles,
y la bondad en su cuidado por las viudas y los huérfanos.
Él mismo era el amor que se exigía entre los hermanos,
la santidad que se demandaba al Sumo Sacerdote,
el verdadero reposo sabático en el séptimo día,
y la sangre expiatoria derramada en cada sacrificio.
Por lo tanto, cuando el Hijo de Dios vino como hombre,
Su propósito no fue enseñar algo diferente, ni abolir algo irrelevante,
sino abrir paso a la sustancia de todo lo que las palabras
y los rituales solo habían representado oscuramente.
Muy lejos de proveer al hombre una manera de quebrantar la ley,
de vivir sin preocuparse por sus justas exigencias,
vino como el cumplimiento de ella y abrió un camino para que todo ser
humano pudiera experimentar este cumplimiento en sí mismo--al nacer,
ser transformado y ser guiado por Su propio Espíritu de justicia.

Por esto dijo:
"`De manera que cualquiera que quebrante uno de estos mandamientos muy pequeños,
y así enseñe a los hombres, muy pequeño será llamado en el reino de los cielos;
mas cualquiera que los haga y los enseñe,
éste será llamado grande en el reino de los cielos`".^
footnote:[Mateo 5:19]
En esencia, está diciendo: "`No ofrezco libertad para quebrantar la ley.
Lo que ofrezco es libertad de la naturaleza de pecado,
para que todo aquel que viva en Mi Espíritu pueda
cumplir la ley`". O en palabras del apóstol:
"`Para que la justicia de la ley se cumpliese en nosotros,
que no andamos conforme a la carne, sino conforme al Espíritu`".^
footnote:[Romanos 8:4]

Y es por esta razón que Jesús concluye este pasaje con estas palabras:
"`Porque os digo que si vuestra justicia no fuere mayor que la de los escribas y fariseos,
no entraréis en el reino de los cielos`".^
footnote:[Mateo 5:20]
Es porque la justicia de los escribas y fariseos no era la justicia de la Sustancia,
sino solo la justicia de la descripción. Era un cuaderno lleno de descripciones y bocetos,
pero no era la esposa viva.
Era la carne tratando de ser santa con un libro en su mano,
pero sin el Espíritu de santidad.

Con esta misma realidad en mente, Pablo nos dice en Romanos 3:21, "`Mas ahora,
aparte de la ley, la justicia de Dios es manifestada,
siendo testificada por la ley y los profetas`".^
footnote:[RVG]
¿Ven la distinción? Ahora, explica Pablo, la sustancia de la justicia,
la naturaleza y la vida mismas de la justicia,
ha llegado aparte de la mera descripción de la justicia
que fue dada en la ley y los profetas.
Ya ha llegado la esposa perfecta, aparte del cuaderno.
Luego concluye: "`¿Luego por la fe invalidamos la ley?
En ninguna manera, sino que confirmamos la ley`".^
footnote:[Romanos 3:31]
O, refiriéndonos una vez más a nuestra analogía, podríamos decir:
"`¿Invalidamos el cuaderno por la llegada de la esposa?
¡En ninguna manera!
Al contrario, su llegada confirma todo lo que antes había sido escrito`".

Todo esto ha sido dicho para demostrar, más allá de toda duda,
_que la única manera en que la ley pierde su jurisdicción,
o su derecho a condenar la naturaleza pecaminosa de la carne en el hombre,
es cuando la Persona de justicia, el cumplimiento de la justicia,
comienza a vivir y a reinar en el corazón_. La ley tiene
jurisdicción sobre todo hombre en tanto viva en la carne.
El requisito justo de Dios tiene derecho permanente
de exponer y reprobar lo que es contrario a Su naturaleza.
Y aunque es una gloriosa verdad que Jesucristo es el cumplimiento de la ley,
el mero hecho de _decirlo_, _comprenderlo_ o _creerlo_ como un hecho,
no hace al individuo libre del pecado,
ni lo exime de las reprensiones y correcciones de los justos requisitos de Dios.
Ni una jota ni una tilde pasará de la ley hasta que toda sea cumplida,
y tanto Jesús como Sus apóstoles nos han informado claramente que
este cumplimiento debe ser experimentado en nuestro _interior_.
