== Eliminando una piedra de tropiezo

Hemos visto que la gracia es el obrar eficaz del poder de Dios en el hombre.
No es una nueva posición o estatus, o un contrato legal,
o un ablandamiento de la ley de la justicia.
Es el poder de Dios, una medida de Su propia vida,
luz y Espíritu que realmente cumple el requisito de justicia en
el hombre al cambiar su corazón. La gracia elimina la condenación,
no eliminando el requisito de justicia,
sino formando la vida justa de Jesucristo en el alma.
La gracia es poder.
Es el poder de una nueva vida, con una nueva naturaleza.

La ley vino por medio de Moisés,
pero la autoridad y el poder para _hacer justo_ al hombre vinieron por medio de Jesucristo.
Y aunque este poder puede ser manifestado exteriormente, aunque puede crear estrellas,
planetas, montañas y océanos, su mayor manifestación y su mayor milagro,
se halla en el corazón oscuro del hombre caído donde
cambia a los hijos de ira en hijos de luz.
La ley describía la justicia, pero la gracia es el poder de la justicia, la bondad,
la vida y el amor, plantado en el alma por el Hijo de Dios resucitado.

Ahora bien, en cuanto a la experiencia del hombre con la gracia,
ésta puede ser comparada con la venida de Jesucristo a Su templo,
el cual había sido durante mucho tiempo una cueva de ladrones;
o con la venida de un hombre fuerte a su casa,
donde otro había tomado previamente posesión de Sus bienes.
Pero tanto la naturaleza de esta venida como la naturaleza de Su incremento,
eran un "`misterio que había estado oculto desde los siglos y edades,
pero que ahora ha sido manifestado a sus santos`".^
footnote:[Colosenses 1:26-27. El contexto de esta
cita se refiere a la presencia de Cristo en el hombre,
nuestra "`esperanza de gloria`". Véase también 1 Pedro 1:10-16,
donde se nos dice que los profetas de la antigüedad "`inquirieron
y diligentemente indagaron acerca de esta salvación`",
y que "`profetizaron de la gracia destinada a vosotros`". En vista de ello,
Pedro nos exhorta a "`poner por completo vuestra esperanza en la
gracia que se os traerá cuando Jesucristo sea manifestado`".]

¿Cuál era este gran misterio?
En una palabra, era la realidad de que, aunque Dios es un Rey grande y poderoso,
Él comienza Su poderoso reino como una pequeña piedra cortada de un monte, no con mano;^
footnote:[Daniel 2:34, 45]
como un grano de mostaza en un jardín entre otras plantas;
o como un tesoro escondido en un campo.
Este es, tal vez, el más grande y más importante "`misterio del reino de Dios`".^
footnote:[Mateo 13:11; Lucas 8:10 RVG]
Ni la aparición externa de Cristo en Israel, ni Su aparición interna en el hombre,
ha venido como un ejército con estandartes,
o como una bomba atómica arrasando con todo a su paso.
No;
Su venida es como un Rey humilde y sin pretensiones que
establece Su trono justamente en medio de Sus enemigos,
y desde allí extiende Su gobierno en aquellos que
rinden su voluntad en el día de Su poder.
Esta es la naturaleza del reino declarado por David en el Salmo 110,
el salmo más frecuentemente citado en el Nuevo Testamento.

[.embedded-content-document]
--

__Jehová dijo a mi Señor: Siéntate a mi diestra,
hasta que ponga a tus enemigos por estrado de tus pies.
Jehová enviará desde Sion la vara de tu poder; domina en medio de tus enemigos.
Tu pueblo se te ofrecerá voluntariamente en el día de tu poder,
en la hermosura de la santidad.__

--

El reinado del poder de Dios no avanza como los reinos de este mundo.
Los reyes de este mundo primero derrotan a sus enemigos,
y luego establecen su trono en una tierra conquistada.
Pero aquí se nos dice que Dios primero establece a Su Rey en medio de Sus enemigos,
y desde allí envía la vara de Su poder,
esperando que sean puestos por estrado de Sus pies.
Él primero unge a Su Rey, lo siembra como una semilla viva en el corazón del hombre,
y luego lo invita a renunciar a su propia voluntad en el día de Su poder; es decir,
cuando la luz amanece en el corazón. Estos dos aspectos
siempre están involucrados en el incremento de Su reino:
por un lado, está la unión voluntaria con el Señor en la luz,
o en "`el día de Su poder`"; por el otro,
está la destrucción continua de la naturaleza incircuncisa.

Se saldría del propósito de este libro decir aquí mucho sobre los
inconfundibles paralelismos y cuadros de estas realidades espirituales
que se nos presentan en las historias del Antiguo Testamento.
Pero permítanme al menos animar a mis lectores a leer la
historia de David teniendo presentes estas verdades.
De muchas maneras, el comienzo,
incremento y reinado de David en la tierra natural de Israel, con todas sus batallas,
tanto contra Saúl como contra los filisteos,
eran cuadros del obrar de la gracia de Cristo en el corazón. El
reino de David era una ilustración dada por Dios de la verdad que,
aunque la gracia comienza con una pequeña unción, puede vencer a todos los enemigos,
rescatar al alma dispuesta, y llenar la tierra del corazón con el reino de Dios.

=== La Palabra de Gracia

Cuando Pablo había estado tres años con la iglesia de Éfeso,
se despidió de ellos con serias advertencias,
informándoles no solo que vendrían "`lobos rapaces`" que no perdonarían al rebaño,
sino también que de entre ellos mismos se levantarían hombres que
hablarían cosas perversas para arrastrar tras sí a los discípulos.
Inmediatamente después de esto, dice:

[.embedded-content-document]
--

__Por tanto, velad, acordándoos que por tres años, de noche y de día,
no he cesado de amonestar con lágrimas a cada uno.
Y ahora, hermanos, os encomiendo a Dios, y a la palabra de su gracia,
que tiene poder para sobreedificaros y daros herencia con todos los santificados.__^
footnote:[Hechos 20:31-32 RVG]

--

Fíjense bien en lo que Pablo está diciendo aquí: "`¡Velen, estén en guardia!
Yo los dejo, pero hay algo que se queda con ustedes.
El peligro viene tanto de dentro como de fuera,
pero hay un poder que permanecerá con ustedes.
¡Los encomiendo a este poder!
Los dirijo a él como su única esperanza.
Es la Palabra de Su gracia, una Semilla de Su gracia, un don del poder vivo de Cristo,
el cual es capaz de edificarlos y darles herencia entre aquellos
que son santificados por él. Esta gracia es su fuerza,
su sabiduría, su experiencia de la salvación de Dios.
Ámenla y crecerán. Obedézcanla y los edificará. Sométanse a ella y los santificará`".

Parece digno de mención en este pasaje que Pablo _no_ dijo: "`Vienen problemas,
viene engaño, pero los encomiendo a mis escritos`". Tampoco dijo:
"`Las cosas se van a poner difíciles,
pero los encomiendo a los líderes y ancianos que he puesto sobre ustedes`". En su lugar,
los encomienda a todos a la Palabra de gracia que (cuando uno se somete
a ella) nunca dejará de guiarlos y fortalecerlos en el camino de vida.
Esta gracia comienza como una pequeña luz en el corazón,
o como un silbo suave y apacible que dice: "`Éste es el camino, andad por él;
y no echéis a la mano derecha, ni tampoco torzáis a la mano izquierda`".^
footnote:[Isaías 30:21]
Y cuando amamos esta luz, comenzamos a encontrar y a sentir su poder.
Vemos que tiene una unción de lo alto para enseñar,^
footnote:[1 Juan 2:27 RVG]
para purificar, para cambiar, para hacer morir y hacer vivir.
La gracia lo hace todo en el creyente cuando es recibida y obedecida.
La gracia _debe_ hacerlo todo en el hombre, porque el hombre, separado de la gracia,
no puede hacer ningún bien.

=== Gracia sin cruz

Pero ahora,
por amor a mis lectores y con el sincero deseo de que todos
experimenten esta Palabra de gracia y su obra en el corazón,
me siento en la obligación de quitar del camino de todo sincero
buscador de la verdad un par de piedras de tropiezo comunes.
No me complace señalar las ideas erróneas,
ni contribuir a la división de una iglesia ya dividida.
Siento una profunda aversión a la controversia, y, por lo general,
considero que el debate es una práctica poco provechosa en el cuerpo de Cristo.
No obstante, debido a que tenemos un enemigo muy real,
quien no desearía nada más que ver a los cristianos terminar su carrera con cabezas
llenas de doctrinas y corazones completamente vacíos de la vida y la naturaleza de Cristo,
me siento obligado a exponer un par de sus más exitosas tergiversaciones.

En el corazón de la humanidad caída,
prevalece una fuerte tendencia a querer parecer mejores de lo que realmente somos.
Este deseo impío es natural en todos nosotros.
De hecho, desde el comienzo mismo del pecado,
el hombre ha tratado de ocultar su verdadera condición detrás de
una variedad de coberturas y teologías hechas de hojas de higuera.
Debido a esto, en la iglesia de hoy, resulta muy atractiva la idea de poseer,
de alguna manera, una justicia que en realidad no experimentamos ni obedecemos;
la de considerarnos santificados sin tener que cambiar;
o la de ser redimidos ante los ojos de Dios aun cuando,
a los ojos de nuestros amigos más cercanos,
claramente _no_ hemos sido redimidos del pecado, la vanidad, la conversación necia,
la lujuria y el amor al mundo.
El hombre está enamorado de la idea de que Dios nos llame "`muertos al pecado`",
aun cuando nuestras decisiones diarias manifiesten que todavía estamos muy bajo su poder.
Nos encanta escuchar a líderes decir que Dios nos ve de una manera,
aun cuando sabemos que nuestros cónyuges dirían algo diametralmente diferente.

Esta gran propensión en el corazón del hombre,
alentada por los susurros de un enemigo invisible,
ha producido un gran menú de doctrinas que, de una forma u otra,
proclaman un tipo de "`gracia`" que puede poseerse y disfrutarse
sin que el hombre tenga que perder su vida,
su voluntad y su tesoro en la carne.
En otras palabras, ha creado una _gracia sin cruz_;
una gracia que no crucifica las pasiones y deseos del primer nacimiento;
una gracia que cubre el pecado sin eliminarlo,
o que libera de las _consecuencias_ del pecado sin
sacar al hombre realmente de debajo de su dominio.

Estas no son simples imprecisiones doctrinales.
Esto es una gracia falsa que, cuando se cree,
obra en el corazón de los cristianos como una enorme barricada,
obstruyendo la experiencia de la redención, silenciando la voz de la convicción,
y resistiendo la obra del Espíritu de verdad.
Y creo que fue precisamente por el atractivo de doctrinas como estas que
los apóstoles se sintieron constreñidos a escribir a la iglesia:
"`Hijitos, nadie os engañe; el que hace justicia es justo, como él es justo`".^
footnote:[1 Juan 3:7]
O, "`¿Qué, pues, diremos?
¿Perseveraremos en el pecado para que la gracia abunde?
En ninguna manera.
Porque los que hemos muerto al pecado, ¿cómo viviremos aún en él?`"^
footnote:[Romanos 6:1-2]
O, "`Pero el fundamento de Dios está firme, teniendo este sello:
Conoce el Señor a los que son suyos; y:
Apártese de iniquidad todo aquel que invoca el nombre de Cristo`".^
footnote:[2 Timoteo 2:19]

Una de las formas en que la _gracia falsa_ ha ganado terreno en la iglesia
es a través de la idea popular de que todo está consumado en nosotros,
tan pronto como decimos la "`oración del pecador`" o "`aceptamos
a Jesús en nuestro corazón`". Hay muchas versiones de esta doctrina,
pero la idea general es que Dios lo ha hecho todo, y, por tanto,
el hombre no puede hacer nada aparte de ver,
disfrutar y descansar en lo que Cristo ya ha cumplido por nosotros.
Algunos malinterpretan las últimas palabras de Cristo: "`Consumado es`",
insistiendo en que esta declaración significa que ya somos perfectos,
y que solo falta la revelación de lo que ya somos.
Esta misma idea suele presentarse con frases ingeniosas como: "`Ustedes ya son justos;
solo necesitan creerlo`". O: "`Dios no ve sus pecados; solo ve a Cristo en ustedes`". O:
"`No se trata de hacer; se trata de comprender`". O: "`El problema no es su condición,
es su percepción`". O: "`Ustedes son tan justos como jamás lo serán;
ahora solo actúen como quienes ya son`".

De nuevo, hay algo muy atractivo para la carne en declaraciones como estas,
pero la verdad es que la gracia no tiene nada que
ver con un cambio imperceptible de estatus,
o con una especie de lente a través de la cual Dios
nos ve de manera diferente a lo que realmente somos.
Consideren por un momento:
¿Cuántos versículos en el Antiguo y el Nuevo Testamento nos dicen claramente,
y de muchas maneras distintas, que Dios '`escudriña el corazón, prueba los pensamientos,
para dar a cada uno según sus caminos, según el fruto de sus obras`'?^
footnote:[Jeremías 17:10 NBLH]
¿Cuántos textos en las Escrituras nos advierten que Dios ve "`los pensamientos
y las intenciones del corazón`" y que "`todas las cosas están desnudas
y abiertas a los ojos de aquel a quien tenemos que dar cuenta`".?^
footnote:[Hebreos 4:12-13]
¿No están _los cristianos_ advertidos de muchas maneras de
que Dios "`traerá a luz lo encubierto de las tinieblas,
y manifestará las intenciones de los corazones`";^
footnote:[1 Corintios 4:5 RVG]
y que cada hombre recibirá "`según lo que haya hecho mientras estaba en el cuerpo,
sea bueno o sea malo`"?^
footnote:[2 Corintios 5:10]
¿No había muchos en la iglesia del primer siglo que afirmaban
ser espiritualmente ricos y no tener necesidad de nada,
cuando en realidad eran "`desventurados, miserables, pobres, ciegos y desnudos`"?^
footnote:[Apocalipsis 3:17]
¿Y no advirtió Cristo que "`muchos`" afirmarían pertenecerle,
haber creído Su doctrina y haber ministrado en Su nombre,
y sin embargo serían rechazados con estas sorprendentes palabras: "`Nunca los conocí;
apártense de Mí, hacedores de maldad`"?^
footnote:[Mateo 7:23]
El Nuevo Testamento abunda en advertencias de este tipo.
Pero, ¿dónde están las Escrituras que nos dicen que Dios no puede ver nuestro pecado,
o que el hombre puede poseer una justicia que no obedece, o en la que no vive?

La verdad sencilla y evidente (de la que toda conciencia
honesta debe dar testimonio) es que,
si el pecado permanece vivo en nosotros como líder,
principio gobernante y fuente de nuestras acciones,
entonces aún no está muerto--por más que afirmemos lo contrario acerca de nosotros mismos.
O, en las palabras irrefutables de Cristo: "`De cierto, de cierto os digo,
que todo aquel que hace pecado, esclavo es del pecado`".^
footnote:[Juan 8:34 RVG]
No podemos pretender ser algo que no estamos viviendo; la gracia no nos da este poder.
El poder de la gracia es real, gratuito y maravilloso,
pero no es un poder para vernos diferentes de como somos;
es un poder para _hacernos_ diferentes de lo que somos, para transformarnos,
limpiarnos y crear en nosotros un corazón nuevo.

Aunque ciertamente hay pasajes que hablan de ser justificados por la gracia,
no se trata de una gracia que justifique al hombre _en su pecado_.
La gracia solo justifica el corazón que la recibe y la obedece.
Permítanme retroceder un poco y explicar brevemente lo que quiero decir.

El propósito de que Cristo viniera como hombre, la razón de Su vida sin pecado,
Su perfecta obediencia, Sus dolores y sufrimientos, Su muerte, sepultura,
resurrección y ascensión, fue porque la humanidad en Adán había muerto a la vida de Dios,
y había quedado atada _por naturaleza_ a los poderes del pecado y de la muerte.
Adán, y toda su posteridad que llevaba su imagen y semejanza,
estaba atrapada por su propio nacimiento en una especie de servidumbre egipcia,
y bajo un amo tan cruel que excedía por mucho los cuadros externos que Dios usó
más tarde para representar esta condición en la historia del éxodo de Israel.

Así como Moisés entró en Egipto,
el Hijo de Dios entró en este mundo y en nuestra condición,
a fin de abrir un camino para salir de él;
y esto se logró principalmente de estas dos maneras: _primero_,
venciendo todo aquello que había vencido a Adán y lo había separado de su Creador;
y _segundo_,
compartiendo después Su vida vencedora con las almas de una humanidad redimida.
Todos los tipos y sombras en el Antiguo Testamento,
los cuatro evangelios y todas las cartas de los apóstoles declaran
y magnifican las maravillosas verdades de esta milagrosa salvación.

En amor inefable,
el Hijo de Dios vino en la naturaleza del hombre
(siendo plenamente Dios y plenamente hombre),
y conquistó cada obstáculo en el camino del regreso del hombre al paraíso.
En perfecta sumisión a la voluntad y al Espíritu de Dios,
el Cordero de Dios venció toda inclinación a la voluntad propia y a la independencia;
todo deseo y apetito que pudiera apartar el corazón del hombre de su Creador;
toda forma de debilidad, hambre, sed y ansiedad; toda clase de tentación,
persecución y ataque demoníaco; las mayores angustias internas y externas,
los mayores dolores emocionales y corporales, y en última instancia, el abandono de Dios,
la muerte física y el sepulcro.
Todo esto se logró, y todo esto fue necesario,
porque el hombre se había puesto a sí mismo bajo el poder de cada una de estas cosas,
y todas ellas eran como puertas y barras que impedían
el regreso del hombre a la unidad con su Creador.
Esta fue la oración de Cristo la noche antes de que fuera traicionado:
"`Que todos sean uno; como tú, oh Padre, en mí, y yo en ti,
que también ellos sean uno en nosotros`".^
footnote:[Juan 17:21]
Esta fue la misión que se le encomendó: unir donde Adán había separado,
"`levantar las ruinas`"^
footnote:[Ver Isaías 44:26, 51:3, 52:9, 58:12 RVG]
y restaurar todo lo que Adán había destruido.
Así, el Hijo de Dios se convirtió en el Hijo del Hombre quien,
en nuestra condición caída, pero sin pecado,
y en perfecta sumisión a Su Padre "`vino a ser autor
de eterna salvación para todos los que le obedecen`".^
footnote:[Hebreos 5:9 RVG]

[.embedded-content-document]
--

Porque convenía que aquel para quien son todas las cosas y por quien son todas las cosas,
llevando muchos hijos a la gloria,
hiciera perfecto por medio de los padecimientos al autor de la salvación de ellos.
Porque tanto el que santifica como los que son santificados, son todos de un Padre;
por lo cual Él no se avergüenza de llamarlos hermanos... Así que,
por cuanto los hijos participan de carne y sangre,
Él igualmente participó también de lo mismo,
para anular mediante la muerte el poder de aquel que tenía el poder de la muerte,
es decir, el diablo, y librar a los que por el temor a la muerte,
estaban sujetos a esclavitud durante toda la vida.^
footnote:[Hebreos 2:10-11, 14-15 LBLA]

--

¡Pero esto es solo la mitad de lo que Cristo ha hecho por nosotros!
Es solo la puerta abierta, el Mar Rojo separado,
y un camino vivo y nuevo abierto en el desierto.
Si esto fuera todo lo que Cristo logró a nuestro favor,
sería en verdad un milagro de amor, pero ni un solo ser humano podría seguirlo y salir.
Sin el nacimiento de Su Espíritu victorioso,
sin el don de una naturaleza más fuerte que la carne,
el hombre solo podría admirar la victoria de Cristo desde lejos.
Pero cuando este Conquistador había vencido el pecado y la muerte,
y regresó a la diestra de Su Padre en el cielo,
entonces derramó Su Espíritu vencedor sobre toda carne,
y visitó a todo ser humano con un poder (llamado _gracia_)
que lo capacita para ver en Su luz y seguir Sus pasos.
Cristo fue el primogénito de entre los muertos,
la Cabeza que abrió el vientre de la muerte y el sepulcro.
Pero esta Cabeza tiene un cuerpo en la tierra que puede nacer de Su vida,
crecer en Su naturaleza, y vencer por Su poder.
Por esta razón Él declara a la iglesia: "`Al que venciere,
le daré que se siente conmigo en mi trono, así como yo he vencido,
y me he sentado con mi Padre en su trono`".^
footnote:[Apocalipsis 3:21]

Jesús no vino como hombre,
no se hizo obediente hasta la muerte ni sufrió en una cruz
para que Dios pudiera vengar Su ira en un sustituto inocente,
ni recibir suficiente satisfacción por Su autoridad ofendida.
Entiendo que estas son ideas populares,
pero no veo nada en las Escrituras que respalde tal visión de la naturaleza de Dios,
ni tal motivación y medio para la salvación del hombre.
No fue la ira de Dios la que envió a Cristo al mundo, sino Su amor; y ese amor vino,
sufrió, murió y resucitó para volver a abrir las puertas eternas,
y compartir el "`poder de una vida indestructible`"^
footnote:[Hebreos 7:16]
con todo aquel que lo quiera recibir.
Esto fue lo que Cristo consumó hace dos mil años. Y este poder redentor
de nuestro Salvador vencedor que nos santifica como Él fue santificado,^
footnote:[Juan 17:19; Hebreos 2:11]
este poder que vence por Su naturaleza vencedora, es llamado _la gracia de Dios._
Este es el "`Espíritu de gracia`"^
footnote:[Zacarías 12:10; Hebreos 10:29]
que es capaz de obrar en el cuerpo de Cristo la misma
victoria que primero llevó a cabo en la Cabeza.

Ahora bien, es enteramente cierto que el hombre es justificado por la gracia,
y no por las obras de la carne ni por las obras de la ley.
Pero debemos tener cuidado de no inventar nuestros propios significados para estas palabras.
Si alguien afirma que es partícipe de la gracia, y, sin embargo,
no vive _en y bajo el gobierno de la gracia,_
entonces esto delata un gran malentendido--el mismo malentendido
que fue rechazado por Pablo con estas palabras:
"`¿Pecaremos, porque no estamos bajo la ley, sino bajo la gracia?
En ninguna manera`".^
footnote:[Romanos 6:15]
En efecto, Cristo ha consumado todo lo que es necesario y todo lo que es posible,
para que el hombre experimente los beneficios de Su obra redentora.
Él nos amó primero, vino en nuestra semejanza, se ofreció a Sí mismo como un sacrificio,
y venció el pecado y la muerte para que el arrepentimiento y el perdón de pecados
pudieran ser ofrecidos en Su nombre a todas las naciones de la tierra.
Rasgó el velo que conduce al Lugar Santísimo,
abrió una puerta para salir de la esclavitud y las tinieblas,
y abrió un camino nuevo y vivo para que los redimidos anden
por él. Despojó al diablo de su derecho a retener las almas,
y quitó la deuda u obligación del hombre con la carne.^
footnote:[Romanos 8:12]
Se convirtió en el perfecto Autor de nuestra salvación,
derribó la pared inamovible de separación y nos introdujo
en pacto con Dios al sembrar una semilla de Su propia gracia,
luz y Espíritu en la tierra de nuestros corazones.
Todo lo imposible ya se ha hecho; la fiesta de bodas está lista,
las invitaciones han sido enviadas,
y todo ser humano ha recibido poder para "`ocuparse en su salvación,
con temor y temblor`".^
footnote:[Filipenses 2:12]
Pero todo esto fue cumplido, no para que Dios nos llame algo que no somos,
sino para que nos haga '`santos, porque el Señor nuestro Dios es santo.`'^
footnote:[Levítico 11:44-45; 19:2; 1 Pedro 1:15-16; Mateo 5:48]

La gracia ha venido como un poder de lo alto.
Pero el hombre debe permanecer en este poder si quiere experimentar su obra,
uniendo continuamente su voluntad a este don y negando
todo lo que es contrario a él. Es una verdad,
más allá de toda duda, que el hombre es justificado por gracia y no por obras;
pero no hay ninguna gracia que justifique al hombre _en el pecado._
La gracia visita al hombre, lo llama a salir del pecado,
y le da poder para permanecer en el Espíritu vencedor de Cristo.
Es como una mano fuerte que entra en Egipto y saca a todo aquel que se somete a su gobierno.
Pero solo aquellos que son gobernados por gracia, que continúan bajo su gobierno,
y vuelven su espalda a la carne y al mundo, son justificados,
santificados y glorificados por ella.
Por eso Pablo y Bernabé persuadieron a las iglesias a "`__permanecer__ en la gracia de Dios`",^
footnote:[Hechos 13:43 RVG]
y por eso el autor de Hebreos advirtió a sus lectores
a que "`ninguno se aparte de la gracia de Dios`",^
footnote:[Hebreos 12:15 RVG]
y que nunca "`ultrajen al Espíritu de gracia`".^
footnote:[Hebreos 10:29 NBLH]

En ningún momento de este evangelio milagroso,
Dios considera que el hombre sea algo contrario a la naturaleza en la que vive,
ni se vuelve ciego a los pecados de la humanidad.
Es cierto--y digno de acción de gracias y alabanza--que incluso un pecador recién convertido,
al apartarse del pecado y del yo, y entregar su vida al don de la gracia,
es justificado del pecado pasado, _porque entonces su voluntad ha salido de él._ Es decir,
cuando Dios ve que hemos cambiado de líderes,
que hemos dejado de seguir el pecado y a Satanás,
y hemos llegado a ser "`obedientes de corazón`" a
las enseñanzas de gracia a las que hemos sido entregados,^
footnote:[Ver Romanos 6:17 "`Pero gracias a Dios, que aunque erais esclavos del pecado,
os hicisteis obedientes de corazón a aquella forma
de enseñanza a la que fuisteis entregados`". LBLA]
entonces somos perdonados y justificados del pecado que ahora aborrecemos.
Aquí el creyente es justificado por gracia,
y ahora debe continuar diligentemente en la gracia
para hacer firme su llamamiento y elección.^
footnote:[2 Pedro 1:10 RVG]
Pero si el corazón no continúa bajo la Mano que lo visitó y llamó a salir de Egipto,
si la voluntad no permanece en sumisión al poder que justifica,
sino que "`cambia la gracia de nuestro Dios en libertinaje`",^
footnote:[Judas 1:4]
entonces esto es lo que el apóstol llama "`caer de la gracia`",^
footnote:[Gálatas 5:4]
o "`recibir en vano la gracia de Dios`".^
footnote:[2 Corintios 6:1]

Es una peligrosa falsedad cuando se les dice a los
cristianos que han llegado al final del camino cuando,
en realidad, muchas veces apenas han comenzado a experimentar la obra de la gracia.
Y no es la verdadera labor del ministro hablar de consuelo,
paz y seguridad a quienes todavía se sienten esclavos del pecado,
viviendo según la voluntad y el camino del primer nacimiento: en los deseos de los ojos,
los deseos de la carne y la vanagloria de la vida.
Las Escrituras ofrecen gran ánimo y consuelo a aquellos
que viven cuidadosa y constantemente bajo la gracia de Dios,
sometiendo su voluntad a su obra que guía, enseña y fortalece.
Pero en ningún versículo se nos anima a descansar en la gracia de ayer.
Cada epístola de Pablo comienza y finaliza expresando el deseo
de que sus lectores continúen creciendo en la gracia de Dios.
Y esto se debe a que Pablo conocía la gracia como un poder creciente,
una semilla viva del reino de Cristo, designada por Dios para crucificar todo egoísmo,
orgullo, envidia, enojo, temor y lujuria, y llenar el alma del poder de la luz,
vida y amor de Jesús.

Permítanme dirigirme a mi lector con las palabras del autor de Hebreos: "`Os ruego,
hermanos, que soportéis la palabra de exhortación`":^
footnote:[Hebreos 13:22]
Por favor, no te contentes con un '`nombre de que vives, si en realidad estás muerto;`'^
footnote:[Apocalipsis 3:1]
o con la afirmación de que la gracia lo ha hecho todo,
si tu corazón todavía encuentra su hogar y su tesoro en este mundo.
No descanses en lo que Cristo ha hecho por ti externamente,
si has experimentado poco o nada de lo que Él desea hacer internamente.
Este ha sido un error extendido en la iglesia desde el tiempo de la Reforma.
Las masas gritan: "`¡La gracia lo ha hecho todo!`",
pero una voz apacible y delicada susurra continuamente en el corazón: "`Pero,
¿qué has permitido que la gracia haga en ti?`"
