== La gracia debe reinar

Desde mi propia y lamentable experiencia, sé que es muy fácil hablar de la gracia,
cantar de la gracia, celebrar la gracia,
incluso mientras se vive una vida cuya naturaleza es contraria a su poder y propósito.
Esto no es raro.
En la actualidad,
existe una gran variedad de definiciones y opiniones sobre la gracia de Dios,
y la gama de ideas sobre este tema puede resultar confusa.
Pero he llegado a ver que cada idea _falsa_ sobre la gracia tiene algo en común:
afirma que podemos poseer y disfrutar las bendiciones de Dios sin perder nuestra vida,
nuestra voluntad y nuestro tesoro en la carne.
En otras palabras,
es una gracia que no crucifica las pasiones y los deseos del primer nacimiento,
no saca nuestro corazón del mundo, ni el mundo de nuestro corazón,
y no nos da poder para vivir sobria, justa y piadosamente en el presente mundo.
Es una gracia que salva de las _consecuencias_ del pecado, sin salvar del poder,
del placer y del reinado del pecado en el corazón. Pero
esta es una gracia que las Escrituras no reconocen.
Observen las palabras de Pablo en Romanos 5:

[.embedded-content-document]
--

__Porque así como por la desobediencia de un hombre los muchos fueron constituidos pecadores,
así también por la obediencia de uno los muchos serán constituidos justos.
Y la ley se introdujo para que abundara la transgresión, pero donde el pecado abundó,
sobreabundó la gracia, [.underline]#para que así como el pecado reinó en la muerte,
así también la gracia reine por medio de la justicia# para vida eterna,
mediante Jesucristo nuestro Señor.__^
footnote:[Romanos 5:19-21 LBLA]

--

Pablo primero nos recuerda que "`la ley se introdujo para que abundara
la transgresión`". El significado de esto debería quedar claro para nosotros
ahora que hemos visto cómo la ley escrita manifestaba el pecado,
pero no tenía poder para eliminarlo.
La ley entró para _describir_ la justicia y _exigir_ la justicia,
pero como no podía _proveer_ la justicia,
sólo hizo que las transgresiones contra la justicia abundaran.

Luego se nos dice: "`Pero donde^
footnote:[La Reina-Valera 1960 traduce este pasaje con "`cuando`" en lugar de "`donde`",
// lint-disable invalid-characters "οὗ"
pero la palabra griega es οὗ, un adverbio de _lugar_ que significa "`donde`".]
el pecado abundó, sobreabundó la gracia`". ¿Dónde abundó el pecado?
Uno podría argumentar que el pecado abundó en el mundo, y, por ello,
la gracia vino al mundo a través de Jesucristo.
En efecto, esto es cierto.
Pero, por el contexto inmediato y el tema de los siguientes tres capítulos,
parece claro que la palabra "`donde`" tiene el propósito de dirigir
la atención del lector más específicamente al corazón del hombre.
El pecado no abundó principalmente en las cosas externas; abundó en el hombre.
Allí era donde se encontraba la enfermedad.
Allí la ley del pecado y de la muerte estaba produciendo sus frutos para muerte.
Allí la ley escrita solo podía exponer y condenar lo que no podía cambiar.
Y es allí también donde la gracia sobreabunda,
o donde obra de una manera aún mayor y más fuerte que la abundancia del pecado.

Aquí llegamos al corazón del argumento de Pablo:
"`Para que así como el pecado reinó en la muerte,
así también la gracia reine por medio de la justicia para vida eterna,
mediante Jesucristo nuestro Señor`". Si le damos a estas palabras la atención que merecen,
me parece que este versículo por sí solo podría poner fin a todos los
malentendidos respecto a la naturaleza y propósito de la gracia de Dios.
Porque aquí, tan claramente como pueden hacerlo las palabras,
Pablo dice que la gracia _debería reinar_ en el hombre a través de la naturaleza de justicia,
así como reinó el pecado anteriormente para muerte.

¡La gracia debe reinar en el hombre tal como ha reinado el pecado!
Pero, ¿cómo ha reinado el pecado?
Creo que todos conocemos muy bien la respuesta a esta pregunta.
El pecado ha reinado en todos nosotros de manera evidente e inconfundible.
Su reino es sutil y engañoso, pero no es invisible ni difícil de percibir.
No hay duda ni debate sobre si el pecado es un poder,
o si hemos experimentado su dominio,
porque todos hemos sentido su fuerza en nuestras mentes,
su influencia en nuestros deseos, y sus frutos en nuestras vidas.
Hemos sentido cómo cambia nuestra manera de ver las cosas, cómo cambia nuestro rumbo,
cómo nos seduce, nos empuja y nos arrastra,
primero avivando nuestros deseos y luego dejándonos decepcionados
y avergonzados mientras envenena nuestra vida.
El reinado del pecado en el hombre es quizás la realidad más demostrable en todo el mundo.
Para observarlo, solo necesitamos mirar por la ventana, leer las noticias,
hablar con un vecino,
o mirar nuestro propio corazón. Tiene raíces y enredaderas
que envuelven todo lo que hace el hombre.
Hace que todos los hombres dancen al son de la flauta,
conduciéndolos hacia una u otra forma de tinieblas, engaño, vacío y vergüenza.
Quien lo niega, ya ha caído bajo su poder.

Pero si solo entendemos esto,
entendemos lo suficiente para saber exactamente cómo
debería reinar la gracia en el hombre,
y cómo debería sobreabundar donde el pecado ha abundado.
Porque, ¿cómo puede reinar el pecado en todas estas formas poderosas, discernibles,
transformadoras del corazón y de la vida, y la gracia no ser capaz de hacer lo mismo?
¿Cómo puede un cristiano confesar que el pecado lo toca todo, atrae y empuja, crece,
llena y contamina de adentro hacia afuera,
y luego decir que la gracia puede ser poseída y disfrutada sin
cambiar nuestro corazón? Pablo dice que donde el pecado abundó,
la gracia abundó "`mucho __más__`",
no "`mucho __menos__`". ¿Es el pecado una naturaleza que reina en el interior,
y la gracia solo una posición legal externa?
¿Destruye el pecado el corazón y la vida de una persona,
y la gracia solo perdona el desastre que el pecado ha causado?

No; la gracia también es una naturaleza interior, un poder vivo,
dado para recuperar la tierra del corazón del reino del pecado.
La verdadera gracia de Dios también empuja y atrae, persuade y enseña,
llena y se extiende, cambia nuestra perspectiva, nuestro corazón y nuestro rumbo.
Purifica donde el pecado ha contaminado.
Habla la verdad donde el hombre ha creído mentiras.
Viene a todos los hombres trayendo salvación,
y los enseña a renunciar a la impiedad y a los deseos mundanos.
Despierta al esclavo que duerme en Egipto, le da poder para salir,
y lo conduce diariamente hacia la Tierra Prometida.
El poder de la gracia puede ser tan demostrable e innegable en las vidas
de los cristianos como lo es el poder del pecado en la gente del mundo.

En 1 Corintios 15:10 Pablo dice: "`Pero por la gracia de Dios soy lo que soy;
y su gracia no ha sido en vano para conmigo, antes he trabajado más que todos ellos;
pero no yo, sino la gracia de Dios conmigo`". En 1 Timoteo 1:14 nos dice:
"`Pero la gracia de nuestro Señor fue más abundante con la fe y el amor que es en Cristo
Jesús`". Es evidente que la gracia de Dios estaba cambiando el corazón de Pablo,
obrando poderosamente tanto en él como a través de él mientras permanecía en ella.
Y aunque no todos somos llamados a ser apóstoles y profetas,
_todos_ somos llamados a caminar en la fe y el amor que son en Cristo
Jesús. Cada creyente es llamado a despojarse del viejo hombre,
a ser renovado en el espíritu de nuestra mente, y a vestirse del nuevo hombre.
Somos llamados a morir al yo, a ser crucificados al mundo, a caminar en el Espíritu,
a no hacer nada "`por contienda o por vanagloria`",^
footnote:[Filipenses 2:3]
a "`ser perfectos, como vuestro Padre que está en el cielo es perfecto`".^
footnote:[Mateo 5:48]
¡Esto requiere poder!
Requiere el obrar eficaz de una naturaleza que reine y abunde
en el hombre donde el pecado ha reinado y abundado.
Y es por esto que debemos entender qué es la gracia y cómo se experimenta.

Volviendo por un momento al pecado, ¿cómo comienza su reinado en el hombre?
Por supuesto,
desde nuestro nacimiento ya hay en nosotros una semilla o naturaleza de pecado.
Todos venimos a este mundo a imagen y semejanza de nuestros padres caídos,
e incluso en la infancia nuestro corazón puede sentir el despertar y la
atracción de una naturaleza contraria a la justicia y la voluntad de Dios.
Pero la pregunta aquí no se refiere a la mera presencia del pecado en el hombre,
sino más bien a su reinado o dominio, a la manera en que crece y gobierna a una persona,
tanto interior como exteriormente.
¿Cómo comienza este reinado, y cómo se incrementa?

Con un poco de reflexión, todos podemos responder a esta pregunta.
No experimentamos la manifestación del poder del pecado como una inundación abrumadora,
ni como un tirano que de pronto toma el mando y derroca nuestra voluntad.
Por el contrario, el pecado comienza como un pensamiento; un mero deseo.
El mundo, la carne o la serpiente presenta una imagen ante la vista de la mente,
junto con la mentira de que poseerla satisfará nuestro deseo
y eliminará la incómoda sensación de anhelo y carencia.
Y cuando la voluntad consiente en ese deseo, o voluntariamente se une a ese pensamiento,
_entonces_ (y no antes) el pecado es concebido y su poder comienza a ganar terreno.
Solo cuando la voluntad del alma _vuelve su atención
y voluntariamente se une_ al deseo del mal,
la semilla de pecado halla cabida, comienza a crecer y gana inercia en la mente.
Esto, repetido una y otra vez, incrementa su reino en el hombre hasta engendrar muerte.
Consideren las palabras de Santiago en el capítulo 1:13-15.

[.embedded-content-document]
--

__Cuando alguno es tentado, no diga que es tentado de parte de Dios;
porque Dios no puede ser tentado por el mal, ni él tienta a nadie;
sino que cada uno es tentado, cuando de su propia concupiscencia es atraído y seducido.
Entonces la concupiscencia, después que ha concebido, da a luz el pecado; y el pecado,
siendo consumado, da a luz la muerte.__

--

¿Cuándo concibe el deseo y da a luz el pecado?
De nuevo,
cuando la voluntad del alma se une voluntariamente a él. El pecado es hijo de _dos_ padres:
1) un pensamiento o deseo malo, y 2) la voluntad del hombre que consiente en ese deseo.
Ser tentado _no_ es pecado, ni tener nuestra atención atraída por pensamientos, deseos,
sugerencias de la carne, o mentiras del enemigo.
Jesús mismo "`fue tentado en todo según nuestra semejanza, pero sin pecado`".^
footnote:[Hebreos 4:15]
Pero lo que Jesús nunca hizo fue unir Su voluntad a una tentación,
y por eso el pecado nunca halló lugar en Él. Es por esto que, justo antes de la cruz,
y habiendo vivido más de treinta y tres años en la tierra como Hombre, pudo decir:
"`Viene el príncipe de este mundo, y él nada tiene en mí`".^
footnote:[Juan 14:30]
Es decir: "`Viene el príncipe de este mundo, pero su naturaleza nunca ha nacido en Mí;
ni una sola vez he unido Mi voluntad a sus pensamientos`".

Por lo tanto,
aunque el pecado está presente como una semilla o una naturaleza
innata en el hombre desde el momento de su nacimiento,
su poder o "`abundante reinado`" crece en respuesta a la actividad de nuestra voluntad.
Cuando damos la bienvenida a la aparición de malos pensamientos y deseos,
hospedamos sus tentaciones,
y voluntariamente nos unimos a sus crecientes sugerencias y promesas,
el pecado va cobrando fuerza como una bola de nieve en nuestros corazones.
Gana terreno, cobra velocidad, peso y tamaño,
hasta que su influencia sobre la voluntad parece casi irresistible.
En algunos, el pecado parece gobernar casi sin obstáculos,
porque han reprimido y entristecido el único poder que se opone a su progreso.
Esta es una terrible condición de esclavitud,
y todo aquel que persista en esa condición hallará
que la paga del pecado es muerte espiritual.

Pero la razón por la que menciono estas cosas no es para glorificar el poder del pecado,
sino para explicar y glorificar el poder de la gracia.
Porque, otra vez, "`donde el pecado abundó, sobreabundó la gracia,
__para que así como el pecado reinó en la muerte,
así también la gracia reine por medio de la justicia`".__
La gracia también tiene una semilla en el hombre,
una semilla sembrada en el corazón por Aquel que está "`lleno de gracia y de verdad`";^
footnote:[Juan 1:14]
y "`de su plenitud tomamos todos, y gracia sobre gracia`".^
footnote:[Juan 1:16]
El buen Sembrador ha salido y sembrado una medida de Su plenitud en todo tipo de terreno,
y esta es la razón por la que la gracia puede abundar donde el pecado ha abundado.
Este don del Espíritu de Cristo--Su gracia en el
corazón--es el fundamento de nuestra esperanza,
y la razón por la que Pedro dice que Él "`nos hizo renacer para una esperanza viva,
por la resurrección de Jesucristo de los muertos`".^
footnote:[1 Pedro 1:3]

Pero, ¿cómo crece el alma en la gracia?
O podríamos preguntar, ¿cómo crece la gracia en el alma?
La gracia es un poder superior, una naturaleza aún más fuerte que la del pecado,
pero su crecimiento en el hombre también depende de la actividad de la voluntad.
No quiero decir que la voluntad del hombre pueda crearla o añadirle algo.
Pero tanto las Escrituras como la experiencia demuestran, más allá de toda duda,
que aquello hacia lo cual nos volvemos, con lo que nos unimos, lo que miramos,
lo que seguimos y lo que obedecemos,
afecta enormemente lo que experimentamos de ambas naturalezas.^
footnote:[Consideren las palabras de Dionysius Freher (1649-1728):
"`Es una verdad constante e inalterable que todo aquello en lo que la mente,
la voluntad y el deseo se ocupan, eso mismo es atraído al hombre,
y el alma llega así a hacerse semejante a ello.
De aquello de lo que se alimenta, a lo que da acogida y de lo que se nutre,
su vida y su imagen crecen en conformidad.
De modo que, cuando la mente, la voluntad y el deseo del hombre, descendiendo,
se ocupaban de cosas sombrías, oscuras, débiles, terrenales, muertas e impuras,
¿qué otra cosa podía adquirir como herencia sino terrenalidad en el cuerpo,
contaminación en el alma y muerte en el espíritu?
Pues fijó sus ojos en tales cosas y se alimentó de ellas con la boca de su deseo.
Pero cuando, por el contrario, mediante el poder que le fue restaurado por Jesucristo,
su mente, su voluntad y su deseo se elevan y se ocupan de la luz y de la vida,
y de los objetos celestiales, puros y sustanciales,
¿cómo podría sucederle otra cosa que aquello de lo cual habla el apóstol cuando dice:
"`Por tanto, nosotros todos,
mirando a cara descubierta como en un espejo la gloria del Señor,
somos transformados en la misma imagen de gloria en gloria,
como por el Espíritu del Señor`"?`"]

Primero, la gracia "`se manifiesta`" en el interior como un don del cielo.
"`La gracia de Dios que trae salvación se ha manifestado a todos los hombres`".^
footnote:[Tito 2:11 RVG]
Una medida de la luz de Dios visita al hombre en las tinieblas,
dándole una visión y un sentido (aunque sea pequeño) de la verdad celestial,
junto con un grano de mostaza de poder para obedecer.
La gracia de Dios nos encuentra en perfecta impotencia y nos ama primero.
En el lenguaje de Ezequiel: "`Y yo pasé junto a ti, y te vi sucia en tus sangres.
Y cuando estabas en tu propia sangre, te dije: ¡Vive!
Sí, cuando estabas en tu sangre, te dije: ¡Vive!`"^
footnote:[Ezequiel 16:6 RVG]
Como Moisés enviado a Egipto, o los ángeles enviados a Sodoma y Gomorra,
la gracia viene y despierta, advierte, invita y da poder para salir.
Este es el comienzo del obrar de Dios en nosotros, "`así el querer como el hacer,
por su buena voluntad`".^
footnote:[Filipenses 2:13 RVG]
Este es el día de las pequeñeces, el talento puesto en la mano.
Y cuando la voluntad se une a este don gratuito, ama su manifestación,
está de acuerdo con su testimonio y cede a su atracción,
la gracia encuentra espacio en el interior para crecer, abundar y, con el tiempo,
"`reinar por la justicia para vida eterna, por Jesucristo, nuestro Señor`".

Pero es de la mayor importancia que no pasemos por alto los _comienzos_ de la gracia.
Porque así como el pecado comenzó su reinado con simples
pensamientos y deseos que atraen hacia el yo,
así la gracia comienza su reinado con pensamientos
y deseos que atraen el corazón hacia Dios.
No me refiero a voces, visiones, o revelaciones profundas.
Sin duda, la gracia también puede producir estas cosas.
Pero ahora solo hablo de aquellas inclinaciones celestiales, convicciones piadosas,
deseos de pureza y pensamientos de una mejor manera de vivir que, de tiempo en tiempo,
aparecen en la mente del hombre.
Hablo de los pequeños frenos y reprensiones por el egoísmo, la vanidad,
el orgullo y la deshonestidad que todos sentimos a lo largo de un día normal.
Hay momentos en los que no podemos evitar suspirar bajo la carga del pecado,
cuando sentimos repulsión hacia el mal y la inmoralidad,
o cuando nuestro corazón se siente atraído más allá de las cosas temporales.
Estos pensamientos y sentimientos descienden de lo alto;
no se originan en el corazón del hombre caído. Son dones
de la gracia que provienen del Padre de las luces,
y son buenos y perfectos según su género.

Si no fuera por la gracia, toda la humanidad estaría confinada a _un solo nacimiento._
De hecho, este es el estado de todos los demás seres terrenales.
No quiero decir que todas las criaturas de este mundo vivan en pecado,
o en una voluntad contraria a la de su Creador.
Simplemente digo que todos los seres creados, excepto el hombre,
experimentan _una sola naturaleza._
Una mula se contenta perfectamente con seguir siendo mula hasta
el fin de sus días. Nunca siente convicciones por su terquedad,
ni reprensiones internas por no compartir su avena.
Un zorro no se siente cargado en la conciencia por robar una gallina.
Un ganso no siente aversión hacia el vicio,
ni una secreta esperanza de que algún día será libre de la vanidad de este mundo.
Pero un hombre siente todas estas cosas porque, en la misericordia de Dios,
la gracia introduce otra naturaleza que llama al hombre a salir de la suya.^
footnote:[2 Pedro 1:4]
Si no fuera por la gracia, el hombre viviría y moriría tranquilo en su primer nacimiento,
donde "`todo designio de los pensamientos del corazón era de continuo solamente el mal`".^
footnote:[Génesis 6:5]
Esta es la condición del hombre en su caída,
y no hay nada en él o de él que pueda hacerlo salir de sí mismo.^
footnote:[Aquí vemos el cumplimiento de toda historia
de éxodo que aparece en las Escrituras (es decir,
la de Abraham, Lot, Israel, Rahab, etc.):
una obra de gracia mediante la cual Dios entra en
el hombre para introducir al hombre en Dios.
Ver Deuteronomio 4:34:
"`¿O ha intentado Dios alguna vez venir __para tomar
para sí una nación de en medio de otra nación,__
con pruebas, señales, milagros, guerra, mano poderosa y brazo extendido,
y con grandes hechos aterradores,
conforme a todas las cosas que Jehová vuestro Dios
hizo con vosotros en Egipto ante vuestros ojos?`"]
Pero la gracia trae una Palabra viva muy cerca del hombre--en su corazón y en
su boca--y por ella Dios no solo pone la vida y la muerte delante de cada alma,^
footnote:[Ver Deuteronomio 30:11-20, y Romanos 10:5-8]
sino que también clama:
"`¡Escoge la vida en lugar de la muerte! ¡Escoge la gracia en lugar de la naturaleza!`"

Esta Palabra de gracia, como ya hemos visto,
es aquel don de poder al que Pablo encomendó a la iglesia de Éfeso.
Toda la esperanza de Pablo para su preservación,
crecimiento y santificación descansaba en ella.
Es una medida de la propia luz de Dios, una semilla de Su Espíritu,
un don de Su Palabra implantada, y, por tanto,
el origen de todo pensamiento _verdaderamente_ bueno.
De la gracia proviene toda convicción del mal, toda aversión al vicio,
todo anhelo de pureza, toda esperanza de escapar de la vanidad,
y todo deseo humilde de conocer y caminar con Dios.
La gracia hace mucho más que producir pensamientos y deseos,
pero aquí comienza su reinado.

La gracia llama al hombre a través de las convicciones por el mal.
Toca a su puerta con buenos pensamientos y deseos.
Aparece como un maestro y ofrece poder para obedecer.
Pero al igual que con el pecado,
_su poder se experimenta en la sumisión de nuestra voluntad_.
Es cuando la voluntad se une a pensamientos y deseos pecaminosos
que comenzamos a sentir el poder del pecado.
Es la unión de la voluntad con las tentaciones lo que lleva al hombre bajo su gobierno.
Y de la misma manera,
cuando la voluntad del hombre se une a la gracia (en la capacidad que ella proporciona),
cuando amamos su testimonio, nos inclinamos delante de ella, abrazamos sus juicios,
y practicamos la verdad que vemos en su luz,
entonces la gracia encuentra un hogar y comienza su reinado.
Aquí es donde la bola de nieve empieza a rodar,
por decirlo así. Aquí es donde el marinero puede izar su vela para aprovechar el viento.

Ahora, para evitar todo malentendido y responder a una objeción común,
permítanme decir que esta unión de nuestra voluntad y sumisión
de nuestras vidas a la gracia que enseña y convence en el interior,
no es ni legalismo ni obras de la carne, sino simple obediencia al Espíritu de Verdad.
¿De qué otra manera podríamos "`vivir en el Espíritu`" y "`andar en el Espíritu`"^
footnote:[Gálatas 5:16, 25]
aparte de una continua sujeción de nuestra voluntad a la guía del Espíritu?
¿Hay alguna manera de negarnos a nosotros mismos, tomar la cruz y seguir a Cristo,
sin una diligente rendición de nuestra voluntad?
Ciertamente no.
Pues Pablo escribe enfáticamente _a la iglesia_ en Roma:
"`Porque si vivís conforme a la carne, moriréis;
mas si por el Espíritu hacéis morir las obras de la carne,
viviréis. Porque todos los que son guiados por el Espíritu de Dios,
éstos son hijos de Dios`".^
footnote:[Romanos 8:13-14]

Si olvidan todo lo que han leído en este libro,
mi esperanza es que recuerden esta única cosa:
que la gracia es el poder de Dios que redime el alma del hombre,
crucifica la naturaleza de pecado,
hace todas las cosas nuevas y todas las cosas de Dios;^
footnote:[2 Corintios 5:17-18]
pero la experiencia de su reinado se encuentra a medida que la
voluntad se une y el corazón se somete continuamente aun a las
primeras y más tenues manifestaciones de Su naturaleza.
El poder de Dios puede exhibirse de muchas maneras,
pero para que un corazón experimente redención,
para que un hombre "`crezca en la gracia y en el
conocimiento de nuestro Señor y Salvador Jesucristo`",^
footnote:[2 Pedro 3:18]
__debe renunciar al primer nacimiento ante cada aparición del segundo.__
Esto es presentarnos "`en sacrificio vivo`"; este es el "`culto racional`"^
footnote:[Romanos 12:1]
de los cristianos.
Así es como el corazón vive bajo la gracia,
y como la gracia se extiende por todo el hombre, para reinar en y sobre todo.

Pero cuando nuestra experiencia de la gracia es pequeña,
somos entonces mucho más propensos a desviarnos.
Cuando no estamos acostumbrados a seguir su voz ni a someternos continuamente a su luz,
y cuando "`los afanes de este siglo, y el engaño de las riquezas,
y las codicias de otras cosas`"^
footnote:[Marcos 4:19]
se sienten más fuertes en nuestros corazones que las enseñanzas de la gracia,
corremos un gran peligro de salirnos de debajo de su reinado.
Este es el caso de muchas pobres almas que son visitadas por la gracia y que,
al igual que Abraham, oyen un llamado a salir "`de tu tierra y de tu parentela,
y de la casa de tu padre, a la tierra que te mostraré`".^
footnote:[Génesis 12:1]
Reciben la Palabra de gracia con gozo,
pero como no llegan a arraigarse y cimentarse en la entrega de su voluntad,
sólo "`son de corta duración`".^
footnote:[Mateo 13:21]
Comienzan a edificar una torre, pero no son capaces de terminarla.
Inician la vida cristiana con un fuerte grito de guerra,
pero poco después "`envían una embajada y le pide condiciones de paz`",^
footnote:[Lucas 14:32]
uniéndose a las filas de aquellos que creen en la gracia, defienden la gracia,
y sin embargo, permanecen ajenos a su poder.

Y es precisamente por esto que los apóstoles exhortaban a los nuevos creyentes a "`perseverar`"^
footnote:[Hechos 13:43; o "`permanecer`" RVG, RV1602P]
en la gracia de Dios, y les suplicaban que no recibieran la gracia de Dios en vano.
El Nuevo Testamento habla de la gracia no solo como un don que se recibe,
sino como un poder o gobierno bajo el cual debemos vivir continuamente.
Por esta razón se nos advierte contra desechar la gracia de Dios, caer de la gracia,
hacer afrenta al Espíritu de gracia,
e incluso cambiar la gracia de nuestro Dios en libertinaje de la carne.
Estas no son posibilidades hipotéticas;
son tentaciones comunes y peligros reales para todos nuestros corazones.
Porque si no ponemos continuamente nuestra voluntad bajo la gracia de Dios,
sin darnos cuenta pondremos la gracia debajo de nuestros pies.

Ahora bien, la expresión "`bajo la gracia`" es una que Pablo emplea en Romanos,
y que con frecuencia se malinterpreta.
En Romanos 6:14 Pablo dice:

[.embedded-content-document]
--

__Porque el pecado no se enseñoreará de vosotros; pues no estáis bajo la ley,
sino bajo la gracia.
¿Qué, pues?
¿Pecaremos porque no estamos bajo la ley, sino bajo la gracia?
¡En ninguna manera!__

--

Para comprender lo que Pablo quiere decir con _bajo_ la gracia,
conviene preguntarse primero en qué sentido estaba Israel _bajo_ la ley.
Creo que es justo decir que Israel estaba bajo la ley _en todo sentido imaginable._
La ley de Moisés gobernaba sobre ellos,
los instruía y regía cada aspecto de sus vidas personales, religiosas y civiles.
Determinaba cómo vivían, cómo se relacionaban los unos con los otros, cómo adoraban,
preparaban la comida, criaban hijos, trataban con el pecado y el mal,
limpiaban sus cuerpos y hogares, respondían a las enfermedades, contrataban siervos, etc.
No había un solo aspecto de sus vidas que no estuviera _bajo_ su jurisdicción,
y sometido a su autoridad.
Sin embargo, a pesar de todo esto, el pecado aún tenía dominio en su hombre interior,
porque (como hemos visto) hay una gran diferencia entre una palabra escrita de la ley,
y una Palabra de gracia implantada.

Pero Pablo dice: "`el pecado no se enseñoreará de vosotros; pues no estáis bajo la ley,
__sino bajo la gracia__`". Estar bajo la gracia no significa ignorar o prescindir de la ley,
como algunos erróneamente creen.
Estar bajo la gracia significa llevar continuamente nuestros corazones, nuestras vidas,
nuestros pensamientos, deseos y obras, _bajo_ el gobierno de la luz y del Espíritu de Dios,
para que así, tal como la ley una vez gobernaba al hombre exterior,
ahora la Palabra de gracia gobierne el corazón y, por medio de él,
también al hombre exterior.

Leamos un poco más de este pasaje en Romanos para comprender
mejor el contexto de esta afirmación. Pablo escribe:

[.embedded-content-document]
--

__Porque el pecado no tendrá dominio sobre vosotros,
pues no estáis bajo la ley sino bajo la gracia.¿Entonces
qué? ¿Pecaremos porque no estamos bajo la ley,
sino bajo la gracia?
¡De ningún modo! [.underline]#¿No sabéis que cuando os presentáis a alguno
como esclavos para obedecerle,
sois esclavos de aquel a quien obedecéis,# ya sea del pecado para muerte,
o de la obediencia para justicia?
Pero gracias a Dios, que aunque erais esclavos del pecado, [.underline]#os hicisteis
obedientes de corazón a aquella forma de enseñanza a la que fuisteis entregados;#
y habiendo sido libertados del pecado, os habéis hecho siervos de la justicia.__^
footnote:[Romanos 6:14-18 LBLA]

--

En otras palabras: "`Ustedes ya no están obligados a ser esclavos del pecado,
porque ya no están bajo el dominio de un mandamiento externo,
sino bajo el gobierno de un poder interior.
¿Significa esto que son libres para pecar porque
no están bajo la autoridad de la letra externa?
¡En ninguna manera! ¿No se dan cuenta de que cuando se entregan como esclavos para obedecer,
son esclavos de aquel a quien obedecen?
Antes eran interiormente esclavos del pecado,
y externamente controlados y condenados por la ley.
Pero gracias a Dios que, aunque eran esclavos del pecado,
han llegado a ser obedientes de corazón a una nueva forma de enseñanza--__la
enseñanza de la gracia__--a la cual fueron entregados.
Y ahora,
habiendo sido hechos libres del poder del pecado
al estar bajo el poder aún mayor de la gracia,
han venido a ser siervos de la justicia`".

Por lo tanto, puesto que la gracia ha venido,
puesto que una medida de Su plenitud ha sido sembrada en nuestros corazones,
y puesto que nuestra única esperanza de salvación se encuentra en ella,
y no en obras de la carne u obras de la ley,
"`acerquémonos con confianza al trono de la gracia`"^
footnote:[Hebreos 4:16]
para abundar más y más en este don bueno y perfecto.
Y tomemos en serio el siguiente consejo de Pedro:

[.embedded-content-document]
--

__Por tanto, ceñid los lomos de vuestro entendimiento, sed sobrios,
y [.underline]#esperad por completo en la gracia que se os traerá
cuando Jesucristo sea manifestado;#
como hijos obedientes,
no os conforméis a los deseos que antes teníais estando en vuestra ignorancia; sino,
como aquel que os llamó es santo,
sed también vosotros santos en toda vuestra manera de vivir; porque escrito está:
Sed santos, porque yo soy santo.__^
footnote:[1 Pedro 1:13-16]

--

=== ¿Gracia Irresistible?

Es evidente que todo lo que se ha dicho aquí sobre la gracia,
junto con los muchos textos bíblicos que demuestran la necesidad
de perseverar en ella y la posibilidad de caer de ella,
no se puede reconciliar con la idea de una "`gracia irresistible`",
comúnmente asociada con Juan Calvino y sus seguidores.^
footnote:[Aunque, para ser justos,
las afirmaciones más categóricas de esta doctrina fueron
hechas por los sucesores e intérpretes de Calvino,
y no por el propio Calvino.]
Según los calvinistas, hay dos tipos de gracia: _la común y la salvadora._
La gracia común es dada a todos los hombres, y es aquella que sustenta la vida,
frena cierta medida de corrupción y mal, y permite que la sociedad humana funcione.
La gracia salvadora, por otro lado,
es considerada un poder imparable concedido únicamente a los elegidos,
que no solo ofrece salvación,
sino que efectivamente la lleva a cabo--produciendo
_irresistiblemente_ en el hombre el arrepentimiento,
la fe y, finalmente, la unión con Cristo.
Sin embargo,
no solo no se menciona en las Escrituras semejante distinción entre dos _tipos_ de gracia,
sino que la idea misma de una gracia irresistible está en desacuerdo tanto con el claro
testimonio de la Biblia como con la innegable experiencia de toda alma humana.

La verdad manifiesta desde Génesis hasta Apocalipsis es que,
aunque Dios es infinitamente más fuerte que el hombre,
éste siempre ha tenido la libertad de resistir Su voluntad y las ofertas de Su poder.
Nada es más claro en la historia de los hombres y de los ángeles.
Dios es omnipotente, pero en Sus tratos con el hombre caído,
nunca ha usado Su poder para forzar a la obediencia ni coaccionar al amor.
Y la razón de esto se fundamenta en la naturaleza misma de las cosas:
la obediencia forzada no es _verdadera_ obediencia,
ni el amor coaccionado es _verdadero_ amor.
La coerción mediante el poder simplemente no es la manera en que Dios establece Su reino.

Si alguna vez hubo un momento en que pudiera pensarse que la gracia era irresistible,
sin duda habría sido en el Paraíso antes de la caída del hombre,
cuando todo permanecía en un estado de perfecta armonía, orden, bienaventuranza y paz.
Pero incluso entonces,
cuando nada en este mundo se había separado de la ley celestial de vida y amor,
el hombre aún poseía la libertad de rechazar la poderosa obra de su Creador.

Y si esto fue cierto en el paraíso, ¡cuánto más lo es en nuestra condición caída,
cuando tanto lo que nos rodea como lo que hay en nosotros
nos tienta y nos seduce a apartarnos de nuestro Creador!
Porque ahora hay una naturaleza en el hombre que persigue con avidez su
propia destrucción. Hay una ley del pecado y de la muerte que no puede
ser desobedecida sino mediante la cuidadosa sumisión a la ley de la vida.
Hay deseos de los ojos, deseos de la carne,
con orgullo y egoísmo que están prontos a mezclarse con todo lo que hace el hombre.
Y hay también una multitud de ángeles caídos que andan como leones rugientes,
buscando cualquier rastro de tinieblas en el corazón del hombre con el que puedan unirse.
No puedo evitar preguntarme cómo alguien puede sugerir que la gracia es irresistible,
cuando la condición del mundo y de la iglesia hace
que muchos crean que el _pecado_ es irresistible.

¿Era la gracia irresistible cuando Dios escogió la descendencia de Abraham
y los llamó a salir de Egipto para que lo siguieran a través del desierto?
¿Era la gracia irresistible cuando Dios introdujo a Su pueblo en la Tierra
Prometida y les mandó que nunca se apartaran de Sus leyes y estatutos?
¿Era la gracia irresistible en los días de los jueces, los reyes o los profetas?
Y ya hemos leído muchos pasajes del Nuevo Testamento en los que los creyentes eran "`persuadidos`"^
footnote:[Hechos 13:43]
por los apóstoles a perseverar en la gracia, y "`exhortados`"^
footnote:[2 Corintios 6:1. Ver también Gálatas 1:6, 2:21, 5:4; Hebreos 12:15, 10:29]
a no recibir la gracia de Dios en vano.

No insistiré más sobre este punto.
Solo deseo que mis lectores reconozcan lo que creo
que no pueden evitar sentir en sus propios corazones:
que el poder de Dios no obra _contra_ la voluntad del hombre.
La gracia redarguye, convence, invita, da poder, y luego transforma el corazón _dispuesto._
Dios ofrece todo lo que es y todo lo que tiene a
todo aquel que tiene hambre y sed de vida eterna.
Pero desde el mismo principio,
esta gracia ha sido experimentada por los que '`quieren y obedecen,`'^
footnote:[Isaías 1:19-20: "`Si quisiereis y oyereis, comeréis el bien de la tierra;
si no quisiereis y fuereis rebeldes, seréis consumidos a espada;
porque la boca de Jehová lo ha dicho`".]
mientras que los orgullosos y egoístas permanecen ajenos a Su poder.
