== El problema

El hombre fue creado a imagen y semejanza de Dios.
Dios dijo:
"`Hagamos al hombre a nuestra imagen y semejanza;`"
y luego sopló en él _Su propio_ aliento de vida.
¿Qué era esta imagen y esta semejanza?
Algunos suponen erróneamente que esta semejanza tenía
algo que ver con la forma o figura del hombre,
o con el hecho de que el hombre camina sobre dos
pies y puede dejarse crecer una barba larga y blanca.
Pero esto no tiene nada que ver con el asunto.
Dios es un Espíritu, y no hay forma, figura ni barba que lleve Su imagen y semejanza.

En toda la creación, solo del hombre se dice que llevaba la imagen y semejanza de Dios,
y esto es así porque solo el hombre fue creado para llevar la luz y el Espíritu de Dios,
para vivir como una rama en la vid de Dios, para andar en Su amor,
para ser partícipe de Su naturaleza y para dar Su fruto celestial.
La capacidad del hombre para llevar la imagen y semejanza de Dios se debía
al hecho de que fue creado para ser templo del Espíritu de Dios,
partícipe de Su vida, amor, justicia,
verdad y sabiduría. El hombre llevaba la imagen de Dios,
porque Dios mismo obraba en él tanto el querer como el hacer por Su buena voluntad.

La imagen y semejanza de Dios no era algo externo.
Tampoco residía en las capacidades intelectuales del hombre ni en su facultad de razonar.
La verdad es que la inteligencia y el pensamiento
racional no tienen bondad ni piedad intrínsecas.
¿Quién no ha visto que muchas de las mentes más brillantes de la historia
han sostenido opiniones ateas y han vivido vidas notoriamente injustas?
Cada día millones de personas usan su facultad de razonar
para ningún propósito mejor que la búsqueda de poder,
alabanza y placeres pecaminosos.
La imagen de Dios no se encuentra en el cerebro.
Previo a su caída,
Adán llevaba la imagen y semejanza de Dios porque
el Espíritu de Dios era el espíritu de su alma.
La vida, la luz, el amor, la justicia, la pureza,
el poder y la sabiduría de su Creador eran la misma naturaleza que lo gobernaba;
y todo lo que pensaba,
deseaba y hacía no eran sino manifestaciones de la bondad
y la gloria que estaban ocultas en el Dios invisible.

En un sentido similar,
uno podría decir que un diamante lleva la imagen y semejanza de
la belleza y del color que están ocultos en los rayos del sol.
Sabemos que hay un arcoíris de colores escondido
en la luz que fluye continuamente del sol.
El color y la belleza están ahí, incluso cuando nuestros ojos son incapaces de verlos.
Pero cuando los rayos del sol pasan a través de un diamante,
el ojo de repente ve destellos y colores que siempre han estado allí. El diamante,
por supuesto, no _produce_ nada de esta luz ni de esta belleza.
De hecho, si pusieras el diamante en una habitación oscura durante cien años,
no haría absolutamente nada,
no manifestaría absolutamente nada y sería indistinguible de la oscuridad.
Pero cuando el diamante se llena de la luz del sol, se convierte en una hermosa vitrina,
una clara revelación y manifestación de todo lo que
es normalmente invisible para el ojo humano.
_En este sentido,_ se puede decir que el diamante lleva la imagen y semejanza del sol.
Recibe, retiene y despliega ante todos los ojos que ven,
las bellezas y colores que están ocultos en la luz.

Pero ahora, si hablaras con un hombre que nació ciego,
y le dijeras que un diamante lleva la imagen y semejanza del sol,
él no tendría ningún marco de referencia para entender lo que quieres decir.
Al no haber visto nunca el sol, solo podría imaginar lo que significa llevar su imagen.
Y así, teniendo un diamante en sus manos,
te podría decir que el sol debe ser duro y frío,
porque eso es lo que encuentra que es cierto del diamante.
Y si le dijeras que está equivocado, en ese caso podría decir: "`Entonces,
el sol claramente tiene bordes afilados y puntas duras que pueden
fácilmente quebrar rocas o tallar imágenes en un trozo de madera.`"
Pero todos los ojos que ven saben que esto no tiene
nada que ver con la imagen y semejanza del sol.

Seguramente entiendes mi punto.
La imagen y semejanza del sol no tiene nada que ver
con lo que el diamante es _en sí mismo,
sin el sol,_
sino más bien con lo que el sol manifiesta de sí mismo en y por medio del diamante.
De la misma manera,
la imagen y semejanza de Dios no tiene nada que ver
con lo que el hombre puede ser _sin la vida de Dios,_
es decir, con lo que el hombre es _en la carne._
Como un diamante en una habitación oscura,
nunca encontrarás la imagen y semejanza de Dios en nada
de lo que el hombre pueda ser o producir por sí mismo.
La única manera en que el hombre alguna vez llevó, o alguna vez llevará,
la imagen y semejanza de Dios es si, como el diamante, recibe,
retiene y despliega las bellezas y maravillas de
la vida y la luz que están escondidas en Cristo.

Ahora bien,
la caída o muerte del primer hombre no fue una muerte de la vasija exterior carnal.
Dios dijo: "`El día que de él comieres, ciertamente morirás.`"^
footnote:[Génesis 2:17]
Sabemos que sí comieron el fruto, y por tanto, ciertamente murieron.
Pero ¿qué fue esta muerte que murieron?

Acerquémonos a la respuesta de esta pregunta comenzando con otra:
¿qué es la muerte natural?
¿Cómo deberíamos definirla?
En pocas palabras,
la muerte natural ocurre cuando el alma eterna del hombre
deja de experimentar la vida exterior de este ámbito físico.
El alma continúa como una creación inmortal,
pero la muerte natural pone fin a su relación con las cosas de este mundo--con la luz,
la vida, el alimento, las criaturas y los placeres de una creación física.

¿Qué es entonces la muerte espiritual,
o la muerte que murió Adán? La muerte espiritual ocurre cuando el alma
del hombre deja de experimentar la vida interna de un ámbito celestial.
De nuevo, el alma continúa existiendo,
pero la muerte espiritual pone fin a la relación del alma con la luz, la vida,
el alimento, las criaturas y los placeres de la creación celestial.
Esta segunda clase de muerte es, por lo tanto, mucho más grave que la primera.
Es la pérdida de algo muy superior a la carne y sangre,
o a las cosas exteriores y temporales.
Es una pérdida, una separación, el fin de la relación con la luz y la vida de Dios.
Es una muerte real a la naturaleza de Dios, una total separación de Su bondad,
una completa pérdida de Su imagen y semejanza.

En la iglesia de hoy,
a menudo se oye que el hombre aún conserva la imagen y semejanza de Dios.
Pero esto no es cierto,
a menos que el hombre haya recuperado lo que perdió. El
hombre fue ciertamente _creado_ a imagen y semejanza de Dios,
pero esta imagen se perdió por completo cuando murió
al reino de la vida de Dios en su alma.
No retuvo la imagen y semejanza de Dios después de
la caída simplemente porque conservó la misma forma,
o porque caminaba sobre dos pies,
le crecía el cabello blanco y mantenía sus facultades intelectuales.
No. La triste realidad es que, habiendo muerto a la vida de Dios,
el hombre comenzó a usar su mente,
su cuerpo y todos los demás dones y capacidades naturales
para manifestar la imagen y semejanza de otro padre,
con otra naturaleza.

Adán perdió la imagen y semejanza de Dios,
y en Génesis capítulo 5 se nos dice que después de que "`Adán vivió ciento treinta años,
engendró un hijo _a su semejanza, conforme a su imagen,_ y llamó su nombre Set.`"
Aquí había una nueva imagen y semejanza;
era como un diamante duro y frío sin la luz del sol.

Ahora bien, conviene decir que el hombre, aún después de la caída,
conserva el mismo propósito.
Es decir, sigue naciendo en este mundo _con el fin_ de llevar la imagen y semejanza de Dios.
Pero, al venir a este mundo nacido de una mujer, no posee naturalmente esta imagen.
La imagen y semejanza que lleva en su condición caída es la de su padre caído;
y de esto dan testimonio las Escrituras en los términos
más claros y contundentes que el lenguaje puede expresar.
Los siguientes son solo unos ejemplos:

[.numbered-group]
====

[.numbered]
_Génesis 6:5 -- Y vio Jehová que la maldad de los hombres era mucha en la tierra,
y que todo designio de los pensamientos del corazón
de ellos era de continuo solamente el mal._

[.numbered]
_Génesis 8:21 -- El intento del corazón del hombre es malo desde su juventud._

[.numbered]
_Jeremías 17:9 -- Engañoso es el corazón más que todas las cosas, y perverso;
¿quién lo conocerá?_

[.numbered]
_Juan 8:44 -- Vosotros sois de vuestro padre el diablo,
y los deseos de vuestro padre queréis hacer._

[.numbered]
_Romanos 3:10-12 -- Como está escrito: No hay justo, ni aun uno.
No hay quien entienda, no hay quien busque a Dios.
Todos se desviaron del camino, a una se hicieron inútiles; no hay quien haga lo bueno,
no hay ni siquiera uno._

[.numbered]
_Efesios 2:1-3 -- Y Él os dio vida a vosotros,
que estabais muertos en vuestros delitos y pecados,
en los cuales anduvisteis en otro tiempo, conforme a la corriente de este mundo,
conforme al príncipe de la potestad del aire,
el espíritu que ahora opera en los hijos de desobediencia;
entre los cuales también todos nosotros vivimos en otro tiempo;
en la concupiscencia de nuestra carne,
haciendo la voluntad de la carne y de los pensamientos,
y éramos por naturaleza hijos de ira, lo mismo que los demás._

====

¿Dirá alguien que estos versículos describen la imagen y semejanza de Dios?
Estos, y muchos otros pasajes similares,
muestran claramente un cambio enorme respecto a nuestra condición original,
una gran caída y pérdida por la cual el hombre llegó
a ser algo completamente distinto de lo que era.
De ser una rama de la bondad, justicia, pureza, amor y vida de Dios,
el hombre se convirtió en una criatura egoísta, orgullosa y codiciosa,
que rápidamente llenó la tierra de violencia y de
toda forma de corrupción. "`Y miró Dios la tierra,
y he aquí que estaba corrompida;
porque toda carne había corrompido su camino sobre la tierra.`"^
footnote:[Génesis 6:12]
O en el lenguaje de Jeremías: "`Y yo te planté como vid escogida,
simiente verdadera toda ella: ¿cómo, pues, te me has vuelto sarmiento de vid extraña?`"^
footnote:[Jeremías 2:21]

Sin embargo, aunque estas cosas se nos declaran una y otra vez en las Escrituras,
no hay en realidad necesidad de textos inspirados,
pruebas exteriores ni profetas enviados por Dios para que el hombre sea consciente
de su condición caída. La evidencia más clara e innegable de la caída del hombre
se halla diariamente dentro de nuestros propios corazones y mentes.
Si tenemos solo la disposición para considerarlo y la honestidad para admitirlo,
estoy convencido de que nadie puede negar estas dos realidades básicas: _primero,_
que todo hombre, de algún modo, conoce lo que es bueno; y _segundo,_
que todo hombre naturalmente--y a menudo de manera irracional--se inclina hacia el mal.
El mal es natural para el hombre y debe ser resistido;
el bien es contrario a su naturaleza y debe ser buscado deliberadamente.

He aquí, entonces, el problema, la enfermedad universal del hombre.
No es una idea ni una doctrina que deba enseñarse y creerse con la mente.
Es un cambio de naturaleza,
una condición patente que se muestra en todo lo que el hombre desea y hace.
Algo terrible ocurrió en el corazón del hombre.
_Murió_ a la luz y al Espíritu de Dios y se convirtió en algo que no era antes.
Y en esta condición,
se manifiesta claramente que lo único que el hombre
necesita hacer para corromperse aún más,
para llevar una vida llena de remordimientos,
y traer dolor sobre su familia y amigos es _¡simplemente
seguir la inclinación de sus propios pensamientos y deseos!_
En Números 15:39 a Israel se le mandó: "`No sigáis vuestro corazón ni vuestros ojos,
tras los cuales os habéis prostituido.`"^
footnote:[LBLA]

[.offset]
Considera también estos versículos de Jeremías:

[.numbered-group]
====

[.numbered]
_11:7-8 -- Porque solemnemente protesté a vuestros padres el día
que los hice subir de la tierra de Egipto hasta el día de hoy,
madrugando, protestando y diciendo: Oíd mi voz.
Pero no obedecieron, ni inclinaron su oído,
antes se fueron cada uno tras la imaginación de su malvado corazón._

[.numbered]
_18:11-12 -- Conviértase ahora cada uno de su mal camino,
y mejorad vuestros caminos y vuestras obras.
Y dijeron: Es por demás; porque en pos de nuestras imaginaciones hemos de ir,
y cada uno de nosotros ha de hacer el pensamiento de su malvado corazón._

[.numbered]
_3:17 -- En aquel tiempo llamarán a Jerusalén: Trono de Jehová,
y todas las naciones se unirán a ella en el nombre de Jehová en Jerusalén;
y no andarán más tras la dureza de su malvado corazón._

[.numbered]
_6:19 -- Oye, tierra.
He aquí yo traigo mal sobre este pueblo, el fruto de sus pensamientos._

====

Seguir sus propios pensamientos hace al hombre cada vez más malo.
¿Qué nos dice esto acerca de nosotros mismos?
Nos dice que tenemos un problema.
Nos dice que no tenemos mayor enemigo que el _yo._

El corazón del hombre se levanta con orgullo,
mira al mundo y usa todo lo que está a su alcance--palabras, dinero, engaño,
fuerza--para atraer las cosas hacia sí mismo.
Cuando tiene éxito, el amor al yo crece.
Cuando fracasa, el amor al yo se vuelve ira.
Cuando otro tiene más, el amor al yo se convierte en envidia.
Cuando se siente amenazado, el amor al yo se convierte en temor.
Habiendo perdido su mayor tesoro--la vida de Dios--es impulsado
a toda forma de egoísmo por la angustiosa sensación de vacío
y el inquietante descontento que no puede evitar sentir.
Y, sin embargo, mientras vive de esta manera,
sabe en lo profundo de su corazón que algo está terriblemente mal,
que esta no es la condición en la cual el hombre vino a este mundo.

Todo hombre sabe qué es bueno, y sin embargo,
todo hombre sabe que él es naturalmente malo.
Si no supiera que es malo, no fingiría ser bueno.
Si no reconociera que existe lo correcto, y que él mismo está en lo incorrecto,
no disfrazaría sus verdaderos motivos ni ocultaría sus verdaderas intenciones.
Pero incluso cuando un hombre reconoce la maldad de sus propias acciones y deseos,
aun así los excusa y justifica, buscando presentarlos como buenos.
Aunque elige hacer las mismas cosas que no tolera en otros,
aun así espera ser considerado diferente de ellos.
Y aunque vive una vida que es contraria a sus propias convicciones,
siendo juzgado por su propia conciencia,
no puede soportar la idea de ser juzgado por otro.

Pregunto otra vez: ¿qué significa todo esto acerca de nosotros mismos?
Significa que algo ha cambiado.
El hombre no es la misma criatura que era antes.
Ya no lleva la imagen y semejanza de su bondadoso Creador.
Ha caído en una condición que es peor de lo que está dispuesto a reconocer,
y allí se esconde de la luz porque sus obras son malas.

Estas palabras fuertes no describen a _otras_ personas;
describen a _todas_ las personas que no han sido hechas libres
de esta naturaleza por la "`obra eficaz`" del evangelio.
Esta es la razón por la que te pregunté si conocías el _poder_ del evangelio.
Las _palabras_ del evangelio no pueden salvar de este problema ni sanar esta enfermedad.
Pero el poder del evangelio puede "`hacer morir las obras de la carne`"^
footnote:[Romanos 8:13]
y dar a luz una nueva creación. El evangelio de Jesucristo no solo te da un nuevo nombre;
te da una nueva naturaleza.
No solo perdona pecados; salva del poder del pecado.
El evangelio es el poder de Dios que obra en el hombre
para restaurar todo lo que estaba perdido,
para crear al hombre de nuevo en Cristo Jesús, para regenerar,
restaurar y renovar la naturaleza y la imagen que el hombre perdió en la caída.

Pero hay otros evangelios que se han hecho populares en nuestros días,
evangelios que no atacan la raíz del problema del hombre, ni sanan su herida mortal.
Hay evangelios que le dan al hombre un nuevo nombre sin hacerlo una nueva creación,
que lo llaman santo aunque vive como un pecador.
Algunos dicen que la gloria del evangelio es que Dios ya no ve pecado en el hombre;
o que, aunque el hombre vive en pecado, es, sin embargo, tenido por justo.
Pero Cristo dice que Él vino para libertar del pecado,
para limpiar lo de dentro del vaso,
para hacer bueno el árbol a fin de que su fruto sea bueno.
El Hijo dijo que podemos ser perfectos como nuestro Padre en el cielo es perfecto;
que podemos andar en la luz, amar a Dios con todo el corazón, alma, mente y fuerzas,
y amar a nuestros enemigos.
Cristo dijo, "`ve, y no peques más.`"^
footnote:[Juan 8:11]
Juan escribió que el Hijo de Dios vino para destruir las obras del diablo en el hombre,
para darnos una simiente que no puede pecar^
footnote:[1 Juan 3:8-9]
y que puede purificarnos así como Él es puro.^
footnote:[1 Juan 3:3]
Pablo dijo que podemos ser transformados "`en la misma imagen, de gloria en gloria,`"^
footnote:[2 Corintios 3:18]
"`hechos conforme a la imagen de su Hijo,`"^
footnote:[Romanos 8:29]
que podemos limpiarnos "`de toda inmundicia de la carne y del espíritu,
perfeccionando la santidad en el temor de Dios.`"^
footnote:[2 Corintios 7:1]

Tal cambio requiere poder, no palabras.
No un poder que llame al hombre algo que no es,
sino un poder que restaure todo lo que el hombre una vez fue.
"`No me avergüenzo del evangelio de Cristo;
porque es poder de Dios para salvación.`" ¿Qué tan bien
conoces la "`obra eficaz`" de este poder del evangelio?
¿Ha creado el evangelio en ti un corazón limpio?
¿Ha limpiado tus pensamientos,
doblegado tu voluntad y llenado tu corazón de nuevos deseos?
¿Te está crucificando al mundo, haciéndote morir al pecado,
fijando tu mente en las cosas de arriba y haciendo que tu corazón crezca en amor?
Si tu respuesta honesta es "`sí,`" entonces ¡alabado sea
Dios!--¡verdaderamente conoces el evangelio de Jesucristo!
Pero si tu respuesta es "`no,`" o "`muy poco,`" entonces puede serte útil
continuar leyendo para entender mejor por qué este podría ser tu caso.
