== "`Los que Aman Su Venida`"

¿Por qué hay tantos cristianos cuyas vidas no evidencian la luz,
la vida y el amor de Jesucristo que el Nuevo Testamento describe en casi cada página?
¿Por qué sus corazones no han sido transformados?
¿Por qué hay tantos que han sido creyentes en Jesús por diez, veinte,
treinta o cuarenta años y, sin embargo, se quejan de una continua esclavitud al orgullo,
al egoísmo, a la lujuria, a la ira, al temor y a los deseos mundanos?
¿Por qué hay tantos que han creído las palabras del evangelio por mucho tiempo y,
sin embargo, han experimentado muy poco de Su poder?

Creo que hay una razón muy específica para esto.
Es porque no reciben el poder de la manera en que viene.
Pablo dice: "`Porque nuestro evangelio llegó a vosotros no sólo en palabra,
sino también en poder, y en el Espíritu Santo, y en plena certidumbre.`"^
footnote:[1 Tesalonicenses 1:5 RVG]
¿Qué significa esto?
¿Qué es este poder?
¿Cómo viene y qué hace?
Estas son preguntas sumamente importantes y,
en lugar de suponer que nunca podríamos pasar por alto o subestimar
la venida del poder de Dios en nuestras propias vidas,
sería sabio considerar estas preguntas con humildad delante del Señor.

La manera en que el hombre comienza a experimentar el poder del
evangelio es mediante una experiencia interna de la luz espiritual.
Las obras de Dios comienzan con la luz de Dios.
Su obra en el mundo externo comenzó cuando Él dijo:
"`Sea la luz,`" y de allí empezó a separar las cosas contrarias,
a traer crecimiento e incremento,
y a hacer que la gloria brotara en la creación exterior.
La nueva creación, con todo su crecimiento y gloria interior, comienza de la misma manera.
El poder viene primero como luz.
Pablo dice:

Que si nuestro evangelio está aún encubierto, para los que se pierden está encubierto;
en los cuales el dios de este mundo cegó la mente de los incrédulos,
para que no les resplandezca la luz del glorioso evangelio de Cristo,
el cual es la imagen de Dios.
Porque no nos predicamos a nosotros mismos, sino a Jesucristo el Señor;
y nosotros vuestros siervos por Jesús. Porque Dios,
que mandó que de las tinieblas resplandeciese la luz,
es el que resplandeció en nuestros corazones,
para iluminación del conocimiento de la gloria de Dios en la faz de Jesucristo.`"^
footnote:[2 Corintios 4:3-6]

Las Escrituras están llenas de expresiones que describen
a Dios o a Cristo como la luz de los hombres,
la luz del mundo, una luz que resplandece en el corazón,
una estrella de la mañana que se levanta en nuestros corazones,
el Cordero que es una luz para la ciudad de Dios, etc.
Por supuesto, sabemos que estos versículos no hablan de una luz natural externa.
Y, sin embargo, la luz espiritual tiene algo en común con la luz natural:
lo "`manifiesta todo.`"^
footnote:[Efesios 5:13 RV1602P]
Permite que los sentidos espirituales perciban lo que es espiritualmente real.
El capítulo 1 de Juan dice:

En el principio era la Palabra, y la Palabra era con Dios, y la Palabra era Dios.
Él era en el principio con Dios.
Todas las cosas por él fueron hechas; y sin él nada de lo que es hecho, fue hecho.
En él era la vida; y la vida era la Luz de los hombres.
Y la Luz en las tinieblas resplandece; y las tinieblas no la comprendieron.^
footnote:[RV1602P]

Los cristianos entienden que estos versículos se refieren a Jesucristo--la
Palabra viva y eterna que _era_ con Dios en el principio,
y _era_ Dios en el principio.
Juan nos dice que la Palabra viva fue el hacedor de todas las cosas,
y que por Él todas las cosas llegaron a existir.
Luego nos dice que en la Palabra era la vida y que esta vida era la _luz_ de los hombres.
Reconozco que estos son versículos familiares,
pero le pido al lector que se detenga por un minuto
y considere de nuevo lo que está siendo dicho aquí:
Juan nos está diciendo que la _vida_ de la Palabra
eterna es la _luz_ que resplandece en los hombres,
aunque la mayoría de los hombres no la comprenden.
O, dicho de otra manera,
que la _luz_ que resplandece en los hombres es la _vida_ de
la Palabra que era con Dios y era Dios en el principio.

En los siguientes versículos, Juan menciona la venida de Juan el Bautista,
y nos dice que él no era la luz,
pero que había sido enviado para dar testimonio de la verdadera luz.
Y entonces, en el versículo 9, hablando de la Palabra, dice:

Aquél era la Luz verdadera, que alumbra a _todo hombre_ que viene a este mundo.
En el mundo estaba, y el mundo por Él fue hecho,
pero el mundo no le conoció. A lo suyo vino, y los suyos no le recibieron.
Mas a todos los que le recibieron, a los que creen en su nombre,
les dio potestad de ser hechos hijos de Dios.^
footnote:[RVG]

Es muy importante sentir el peso de estas verdades.
En la Palabra que hizo todas las cosas había una vida,
y esa vida era la verdadera luz de los hombres.
Esta luz resplandece en alguna medida, o en cierto grado,
en todo hombre que viene a este mundo.
Pero, aunque el mundo fue hecho por Él, y aunque Él resplandece en todos,
aun así el mundo puede fácilmente permanecer en un
estado en el que no Lo conoce ni Lo recibe.
Pero, a todos los que sí reciben Su luz, Él les da la potestad^
footnote:[La King James Version traduce esta palabra "`power`", es decir, _poder._
// lint-disable invalid-characters "ἐξουσία"
_Potestad_ también es una traducción válida de la palabra griega ἐξουσία,
pero hay varios lugares en la Reina Valera 1960 donde la palabra se traduce _poder_,
y parece la traducción más adecuada en este contexto.]
de ser hechos hijos de Dios.

Sé que muchos han entendido estos versículos como si se refirieran exclusivamente
a la venida externa de Cristo a los judíos del primer siglo,
y es verdad que la mayoría del pueblo judío no recibió dicha venida.
Pero, puesto que Juan está hablando aquí de la Palabra
eterna como el creador de _todos los hombres,_
y como una luz que alumbra a "`todo hombre que viene a este mundo;`"
y puesto que se dice que esta luz alumbra con el propósito de que
"`por él _todos_ creyesen,`" y no solo los judíos del primer siglo,
considero seguro concluir que estas Escrituras están hablando en un sentido más amplio.
En otras palabras,
parece que Juan tiene en mente _toda forma_ de "`aparición`" o "`manifestación`" de Cristo,
y no solo Su aparición física por tres años y medio
en un lugar y tiempo específicos en el mundo.
Esto se confirma por el hecho de que Juan no introduce
la encarnación hasta el versículo 14,
donde dice: "`Y la Palabra fue hecha carne, y habitó entre nosotros.`"

Ahora bien, es sumamente importante notar que, aunque esta luz (la cual, de nuevo,
es la vida de la Palabra eterna) resplandece en las tinieblas del hombre, sin embargo,
solo a los que Le _reciben_ se les da potestad, o poder, de _ser hechos_ hijos de Dios.
Aquí mismo está la respuesta a nuestra pregunta,
si tan solo entendemos qué significa "`recibirle.`"
Esta es precisamente la razón por la que tan pocos
experimentan la "`obra eficaz`" del poder del evangelio.
Es porque solo los que reciben esta luz, aquellos que aman Su venida, aceptan,
siguen y obedecen Su resplandor,
experimentarán el poder de _ser hechos_ hijos de Dios--es decir,
recibirán poder para ser transformados de nuevo a Su imagen y semejanza.

¿Has considerado alguna vez con atención los versículos en el Nuevo
Testamento que hablan de la "`venida`" del Señor? Hay varios que
no pueden referirse a un acontecimiento físico en el futuro.
Por ejemplo, Pablo dice: "`Así que, no juzguéis nada antes de tiempo,
hasta que venga el Señor, el cual también traerá a luz lo encubierto de las tinieblas,
y manifestará las intenciones de los corazones.`"^
footnote:[1 Corintios 4:5]
¿Es razonable creer que esta Escritura prohíbe toda forma de juicio (en nuestras vidas,
doctrinas, familias, la iglesia,
etc.) hasta que haya una venida futura y externa de Cristo?
¿No contradiría esto las propias palabras de Pablo
en el capítulo siguiente de la misma carta?
1 Corintios 5:3: "`Ciertamente yo, como ausente en cuerpo, pero presente en espíritu,
ya como presente he juzgado al que tal cosa ha hecho.`"
O 1 Corintios 5:12: "`Porque ¿qué razón tendría yo para juzgar a los que están fuera?
¿No juzgáis vosotros a los que están dentro?`"

En el capítulo 5 de su epístola,
Santiago compara la "`venida del Señor`" con el precioso fruto
que brota de la tierra en aquellos que pacientemente Le esperan.
(Véase Santiago 5:7-8) Apocalipsis 3:20 habla de Cristo "`entrando
y cenando`" con aquellos que oyen Su voz y Le abren.
Ninguna de estas Escrituras se refiere a un acontecimiento futuro,
o a un traslado físico de un lugar a otro.
Pero me gustaría llamar tu atención específicamente a 2 Timoteo 4:8, donde Pablo dice:
"`Por lo demás, me está guardada la corona de justicia, la cual me dará el Señor,
juez justo, en aquel día; y no sólo a mí, sino también a todos los que aman su venida.`"
Algunas Biblias en español traducen "`manifestación`"
en lugar de "`venida;`" pero en cualquier caso,
los lectores a menudo suponen que Pablo está hablando
exclusivamente de un acontecimiento futuro.

Para ser claro, creo de manera absolutamente inequívoca que Cristo _ha_ venido en la carne,
que vivió treinta y tres años como hombre, fue crucificado, sepultado,
resucitado de entre los muertos y ahora está sentado a la diestra de Dios.
También creo que un día Él se manifestará abiertamente a todo el mundo,
pondrá fin al tiempo y a la creación temporal, y juzgará a los vivos y a los muertos.
Pero en 2 Timoteo 4:8, parece más allá de toda duda,
que esta venida o aparición no puede referirse ni
a un acontecimiento pasado ni a uno futuro.
Considera por un momento:
¿qué podría significar amar una venida _futura y física_ de Cristo?
Ciertamente no puede significar mirar continuamente
al cielo con la esperanza de ver una aparición externa.
Pero ¿puede significar solamente amar nuestras ideas
acerca de lo que Cristo podría hacer en el futuro?
¿Cómo podría ser esto un ejercicio de verdadero valor?
¿Y cómo sería este el camino para alcanzar una corona de justicia?
¿Terminó Pablo su carrera, se presentó ante el tribunal, y dijo:
"`Estoy preparado para recibir mi corona de justicia
porque me gustaba imaginar Tu venida externa,
aunque nunca ocurrió en mi vida`"? ¿Puede ser algo
así lo que Pablo está comunicando a Timoteo?

Sin embargo,
lo que _sí_ tiene sentido--muchísimo sentido--y lo que comprensiblemente
es de la mayor importancia para cada cristiano,
en toda época, es la necesidad de amar,
recibir y obedecer al Hijo de Dios en la manera en que Él "`viene`" o "`aparece`" hoy.
¿Y cómo viene a nosotros hoy?
Viene a nosotros como luz, resplandeciendo en nuestras tinieblas; y, aun así,
_muchos_ no aman Su venida.

Esto es precisamente lo que Jesús describe en Juan
capítulo 3 en Su conversación con Nicodemo.

Y ésta es la condenación: que la luz vino al mundo,
y los hombres amaron más las tinieblas que la luz, porque sus obras eran malas.
Porque todo aquel que hace lo malo, aborrece la luz y no viene a la luz,
para que sus obras no sean reprendidas.
Mas el que practica la verdad viene a la luz,
para que sea manifiesto que sus obras son hechas en Dios.^
footnote:[Juan 3:19-21]

Aquí leemos que la luz _viene_ al mundo, pero en lugar de amar Su venida,
los hombres aman más las tinieblas que la luz.
¿Y por qué aman las tinieblas?
Porque sus obras son malas,
y sienten cómo la luz reprueba sus obras y se opone a sus deseos.
Pero te pregunto: ¿cuándo viene esta luz?
¿Y cómo viene?
¿Puede este versículo limitarse a la venida externa
del Hijo de Dios en una sola región del mundo,
durante un breve momento de la historia?
¿Era posible que los hombres vieran sus malas obras y vinieran a la luz solamente
cuando Cristo anduvo como hombre hace dos mil años? ¿O es todavía Cristo una
luz que viene en las tinieblas y enseña a los hombres a practicar la verdad?

Presento estas cosas a tu consideración porque siento que es de
la mayor importancia comprender los siguientes tres puntos:

Primero, con respecto a la venida de Cristo,
que aunque Él ciertamente vino como el Hijo del Hombre e
Hijo de Dios en un cuerpo que Dios '`preparó para Él,`'^
footnote:[Hebreos 10:5]
y aunque vendrá "`como ladrón en la noche;
en el cual los cielos pasarán con grande estruendo,
y los elementos ardiendo serán deshechos,`"^
footnote:[2 Pedro 3:10]
también viene ahora, en diferentes medidas o grados,
en todo hombre que viene a este mundo,^
footnote:[Juan 1:9 RVG]
como la "`luz del mundo +++[+++entero],`"^
footnote:[Juan 8:12]
y no solo una luz para el Israel del primer siglo.

Segundo,
que esta venida de la luz de Cristo manifiesta o expone aquello
que es malo o contrario a la naturaleza y la voluntad de Dios.
Efesios 5:13 "`Pero todas las cosas que son reprobadas,
son hechas manifiestas por la luz, porque lo que manifiesta todo, es la luz.`"^
footnote:[RVG]

Tercero, que el hombre tiene la capacidad, o más bien la tendencia,
de "`no recibir,`" de "`aborrecer`" y de "`resistir`" esta venida de la luz, y por tanto,
de no recibir su poder ni experimentar el propósito de su venida.

Entonces, ¿quién es el que experimenta la "`obra eficaz`" del poder del evangelio?
Solo aquellos que aman, abrazan y obedecen Su venida.
Es decir,
solo los que inclinan su cerviz y unen su voluntad a todo lo que la luz pone de manifiesto;
los que con mansedumbre reciben sus golpes y practican su verdad,
en lugar de esconderse en las tinieblas de sus propias opiniones y deseos.

El Día de las Pequeñeces

Hay grandes malentendidos acerca de la venida de la luz de Cristo,
y grandes imaginaciones acerca de _cómo_ viene y _qué_ hace.
De hecho,
creo que hay tantos malentendidos acerca de la aparición
interna de la luz de Cristo en el corazón,
como había acerca de la aparición externa de Cristo en los días de Su carne.

Cuando Cristo vino externamente,
no fue en absoluto de la manera en que los judíos esperaban.
Ellos estaban esperando algo inconfundible e innegable,
algo que resolviera los problemas que percibían y
se alineara con sus interpretaciones de las Escrituras.
Pero el Mesías largamente esperado vino como un bebé en
un pesebre y trabajó muchos años como carpintero en Nazaret.
Comenzó Su ministerio declarando que el tiempo se había cumplido,
y que la hora había llegado para que Dios estableciera un reino en el
hombre--un reino interno donde el Rey conquistaría un enemigo interno.
Recorrió las calles de Israel testificando,
no contra enemigos externos e injusticias sociales, sino contra toda forma de pecado,
maldad e impureza que había convertido el corazón
del hombre (el templo de Dios) en una cueva de ladrones.
Aunque vino en el insondable amor de Dios para buscar y salvar lo que estaba perdido,
aun así "`hirió la tierra con la vara de su boca,`"^
footnote:[Isaías 11:4]
llamando a muchos hipócritas, hijos del diablo, sepulcros blanqueados,
vasos y platos que estaban sucios por dentro,
árboles con raíces malas que no podían producir buen fruto.
Él dijo a Sus propios hermanos: "`No puede el mundo aborreceros a vosotros,
mas a mí me aborrece, porque yo testifico de él, que sus obras son malas.`"^
footnote:[Juan 7:7]
Les enseñó que la impureza procede del interior,
no de tocar alimentos con manos sin lavar.
Dijo que eran hijos de la carne que necesitaban nacer del Espíritu,
un pueblo necesitado de una justicia que superara la de los escribas y fariseos.
Y todo esto fue dicho a hombres y mujeres que poseían las leyes
de Dios y se consideraban Sus únicos verdaderos adoradores.

Así vino Jesucristo en la carne, y no fue en absoluto lo que ellos esperaban.
Muchos de ellos amaban los milagros que sanaban sus cuerpos y llenaban sus estómagos,
pero no les agradaban Sus palabras,
y se ofendían en gran manera por Su misión. "`Linaje de Abraham somos,
y jamás hemos sido esclavos de nadie.
¿Cómo dices tú: Seréis libres?
Jesús les respondió: De cierto, de cierto os digo, que todo aquel que hace pecado,
esclavo es del pecado.`"^
footnote:[Juan 8:33-34]
Así que, muy lejos de recibir`" y "`amar Su venida,`" la aborrecieron,
la negaron y buscaron la manera de matarlo, aun mientras continuaban leyendo sus Biblias,
asistiendo a sus sinagogas y esperando un Mesías que mejor se ajustara a sus expectativas.

¿Qué dirías si te dijera que esto sigue ocurriendo hoy?
Israel pasó por alto,
rechazó y luego crucificó a Su Salvador porque no le gustó la manera en que Él
se les manifestó. Pero el tiempo no ha cambiado el corazón del hombre.
En su condición natural, todavía es la misma criatura ciega,
prejuiciosa y orgullosa que rechaza la luz que testifica contra ella.

La venida de la luz de Cristo en el corazón hoy no es diferente de Su venida en Israel.
Por supuesto, es una manifestación _interior_ en lugar de una _exterior,_
pero _es exactamente el mismo Jesucristo,_ con la misma naturaleza,
poder y misión. El mismo Mesías que vino externamente ahora viene internamente,
y la naturaleza caída y orgullosa del hombre Le da exactamente la misma acogida.

Ahora ten mucho cuidado de no excusarte apresuradamente de esta advertencia.
El hecho de que ames al Jesús histórico de la Biblia,
no significa que ames la luz y el poder de Jesús que aparece en tu corazón.
Los judíos del primer siglo amaban a Moisés y a los profetas.
Citaban las palabras de los profetas,
adornaban sus tumbas y creían firmemente que vivían según sus doctrinas.
Multitudes en Israel alababan, memorizaban y enseñaban las palabras de los profetas,
aun cuando en sus corazones eran completamente contrarios
al Espíritu que hablaba a través de ellos.
Más aun,
los judíos del primer siglo incluso encontraron la manera de usar las palabras
de Moisés y de los profetas para acusar y crucificar a su Salvador--¡Aquel mismo
de quien Moisés y los profetas habían escrito!

Los cristianos de hoy piensan que es increíble que los judíos de antaño
pudieran ser tan ciegos y duros de corazón. Pero no te ofendas si te digo
que hacemos exactamente lo mismo con las palabras de Jesucristo.
Han pasado dos mil años,
y la gente ha llegado a estar muy familiarizada y
demasiado cómoda con las palabras en rojo de la Biblia.
Pero es fácil amar Sus dichos y, sin embargo,
aborrecer Su naturaleza cuando aparece en nuestro corazón como luz.
Es fácil disfrutar las historias y las canciones acerca de Jesús,
maravillarnos ante Su sabiduría y Sus milagros, e incluso creer todas Sus palabras,
pero cuando la luz de Su vida resplandece en el corazón, manifestando egoísmo, orgullo,
palabras vanas y malos deseos,
no "`amamos Su venida,`" sino que más bien "`amamos las tinieblas más que la luz.`"
Estamos seguros de que nunca habríamos estado entre
los que crucificaron al Señor de gloria y,
sin embargo, en la ciudad invisible de nuestro corazón,
a menudo "`crucificamos de nuevo para nosotros mismos
al Hijo de Dios y lo exponemos a vituperio.`"^
footnote:[Hebreos 6:6]

De nuevo, por favor no supongas que esto es una imposibilidad para ti.
Siempre ha habido creyentes que tienen celo por Dios y por la justicia,
pero que no _se sujetan_ a la justicia que viene de Dios.
Hablando de sus compatriotas según la carne, Pablo dice:

Porque yo les doy testimonio; de que ellos tienen celo de Dios, mas no según conocimiento.
Porque ignorando la justicia de Dios, y procurando establecer su propia justicia,
no se han sujetado a la justicia de Dios.^
footnote:[Romanos 10:2-3 RV1602P]

Te confieso abiertamente que yo fui uno de ellos,
aun cuando trabajaba como líder en la iglesia.
Hay una gran diferencia entre amar la justicia de Cristo fuera de nosotros,
y sujetarse a la justicia de Cristo dentro de nosotros.
Hay una gran diferencia entre amar las palabras de Cristo y amar la luz de Cristo.
Cuando un hombre lee las palabras de Cristo en las tinieblas de la mente natural,
pueden significar cualquier cosa.
Pero cuando la luz de Su vida aparece en el corazón,
hay una visión y un sentir de la Verdad que no necesita interpretación.
He hallado en mi propia vida que es posible leer,
cantar e incluso predicar las palabras de Cristo,
y al mismo tiempo aborrecer Su venida tanto como los fariseos de corazón duro lo hicieron.
¿Y por qué la aborrecía? La aborrecía por la misma razón que los fariseos;
porque amenazaba algo que yo amaba.
Sentía muy poca amenaza al oír las palabras del evangelio,
pero la luz o Palabra del evangelio era una amenaza para la vida del _yo._

Nadie afirma abiertamente aborrecer la venida o aparición de Cristo.
Los fariseos del primer siglo nunca habrían confesado despreciar la venida de su Mesías,
y los cristianos hoy son tal vez aún más reacios a esa idea.
Pero lo único que se necesita hacer para aborrecer la luz es discrepar,
ignorar o resistir lo que ella revela.
"`Amar las tinieblas más que la luz`" es simplemente
rehusar aceptar y sujetarse a lo que manifiesta,
y esto rara vez se hace con palabras.
Es el corazón el que niega la luz de Cristo.
Quiero decir, nuestras decisiones Lo niegan; nuestros pensamientos,
búsquedas y deseos Lo contradicen a lo largo del día, aun sin decir una sola palabra.
Y es precisamente de esta manera,
en distintos grados y en cientos de pequeñas decisiones,
que todos nosotros hemos rechazado la luz de Cristo,
y así no experimentamos un crecimiento en el poder de Su evangelio.

Ahora bien, cuando digo que Cristo viene por medio de Su luz en el corazón,
no debes imaginar que me refiero a visiones, sueños o incluso palabras habladas.
Cristo es la Palabra viva de Dios,
la perfecta comunicación y manifestación de la naturaleza y esencia de Dios.
Hebreos declara que Él es "`el resplandor de su gloria,
y la imagen misma de su sustancia.`"^
footnote:[Hebreos 1:3 ]
Cristo es la sustancia viva de la bondad,
del amor desinteresado y de la santidad perfecta.
Su misma naturaleza es humildad, justicia, mansedumbre, bondad y pureza.
Y cuando esta naturaleza hace sentir Su presencia en el corazón,
rara vez lo hace con palabras que el hombre deba percibir o interpretar.
La venida o aparición de Cristo es un ver interior de quién es, y qué es Él,
y en esta luz viene una percepción incómoda de quiénes y qué somos nosotros.`"

Por ejemplo,
un vislumbre de Su luz trae un sentido de lo que es verdaderamente bueno y justo,
y junto con ella viene una desagradable convicción de nuestro
propio egoísmo o injusticia--quizás en algo que hicimos,
pensamos, dijimos o deseamos.
Algo en nuestro interior nos hace ver que nuestras
acciones o motivaciones son contrarias a la Verdad,
o inconsistentes con la naturaleza de Dios.
Quizás experimentamos una punzada en nuestra conciencia por actuar desde el orgullo,
la vanidad, el egoísmo o la ira,
por usar nuestras palabras para llamar la atención sobre nosotros mismos,
o por nuestra manera de vestir para lucir nuestro cuerpo o nuestra riqueza.
O tal vez,
sentimos una conciencia persistente (aunque tratamos de sofocarla)
// lint-disable mid-word-uppercase "YouTube"
de que estamos malgastando tiempo precioso en YouTube,
Netflix, redes sociales o leyendo libros que no son de provecho.
A estas cosas muchos cristianos las llaman "`pequeñeces,`" y generalmente
creemos que tienen poco que ver con nuestro crecimiento espiritual
y con nuestra experiencia del poder de Dios.
Por lo común prestamos muy poca atención a estas advertencias y reprensiones,
y a menudo tanto los padres como los pastores nos enseñan (con sus palabras
y con su ejemplo) que no debemos permitirnos sentir culpa o vergüenza.
De muchas maneras somos animados a seguir la corriente de nuestra sociedad,
de nuestros amigos, de nuestra cultura, de lo que vemos en internet o en la televisión,
en lugar de prestar atención al "`silbo apacible y delicado,`"^
footnote:[1 Reyes 19:12]
a ese inquietante sentimiento que punza nuestro corazón cuando nuestra
vida y nuestras decisiones contradicen la naturaleza de Dios.
Pero la verdad es--y todos los que alguna vez hayan obedecido la luz testificará conmigo--que
estas pequeñas convicciones y correcciones son los comienzos del poder de Dios,
las primeras apariciones de la "`luz de la vida.`"

¿Dirá alguien que estas "`pequeñeces`" no tienen nada que ver con su vida espiritual,
cuando está claro que tienen todo que ver con su corazón? ¿No es Dios el Dios del corazón?
¿Hay algo más importante para Él que lo que el corazón del hombre hace y busca?
¿Dirías que estas pequeñeces--como la ropa, las bromas,
el entretenimiento y los teléfonos--no son importantes para
Dios cuando claramente son muy importantes para ti?
Y si estas cosas ya ocupan tanto de tu corazón, de tu tiempo y de tu lengua,
¿esperas que Dios comience a hablarte acerca de algo más?

¿Y de dónde crees que vienen estos sentimientos de incomodidad
y reprensión? ¿Brotan de la naturaleza de la carne caída y perversa?
¿Se está reprendiendo tu carne a sí misma?
¿Quedó algo inherentemente bueno en el hombre después de
que murió a la vida de Dios--el hombre del que Dios testificó:
"`el intento del corazón del hombre es malo desde su juventud,`"^
footnote:[Génesis 8:21]
y "`todo designio de los pensamientos del corazón
de ellos es de continuo solamente el mal`"^
footnote:[Génesis 6:5]? ¿O dirás que estas convicciones contra el mal
y impulsos hacia la justicia provienen del acusador de los hermanos,
el enemigo del alma del hombre?
¿Está el reino de Satanás dividido contra sí mismo?

Algunos podrían decir:
"`¡Estos sentimientos de reprensión o condenación
por el pecado no pueden provenir de Dios,
porque Dios me ama!`"
Pero es precisamente _porque_ Dios te ama que Él te permite sentir
lo que es contrario a Su naturaleza y se opone a tu propio bien.
La luz trae juicio y convicción de pecado no para que vivas bajo condenación,
sino para que te vuelvas de los deseos de la carne, aprendas a andar en el Espíritu y,
así, salgas de la condenación.

Esto es precisamente lo que Pablo nos dice en Romanos capítulo 8: "`Ahora, pues,
ninguna condenación hay para los que están en Cristo Jesús,
los que no andan conforme a la carne, sino conforme al Espíritu.`"
No hay condenación para aquellos que andan conforme al Espíritu.
¡Pero,
por supuesto que sí hay un sentido de condenación y desaprobación cuando aquellos
que han recibido el don del Espíritu continúan andando conforme a la carne!
Por supuesto que Dios nos permitirá sentir Su enemistad y Su desacuerdo
con la naturaleza que es contraria a Él en todo sentido--una naturaleza
de la que se nos dice que "`codicia contra el Espíritu,`"^
footnote:[Gálatas 5:17 RVG]
y es "`enemistad contra Dios.`"^
footnote:[Romanos 8:7]
Los sentimientos de rechazo dirigidos al creyente en lugar de al pecado,
acompañados de acusaciones de ser un caso perdido, un fracaso o una decepción,
son a menudo obra del "`acusador de los hermanos.`"^
footnote:[Apocalipsis 12:10]
Pero la conciencia de pecado,
las convicciones de mal y los impulsos hacia la justicia son los dones de un
Dios misericordioso que quiere vivir con el hombre en Su propio Espíritu puro.

Algunos alegan que estas convicciones y reprensiones son
las operaciones de la "`conciencia natural`" del hombre.
Pero Pablo nos dice claramente que: "`Todas las cosas que son reprobadas,
son hechas manifiestas por la luz, porque lo que manifiesta todo, es la luz.`"^
// lint-disable invalid-characters "ἐλέγχω"
footnote:[Efesios 5:13. La palabra griega _ἐλέγχω_ significa reprender,
redargüir o convencer, tal como es traducida en la RVG.
Algunas versiones la traducen como "`exponer`" o "`poner en evidencia`"
o "`dejar al descubierto`" lo cual puede suavizar el sentido de
convicción y reprensión que tiene el término original.]
Cristo dice: "`Y ésta es la condenación; que la luz vino al mundo,
y los hombres amaron más las tinieblas que la luz, porque sus obras eran malas.
Porque todo el que hace lo malo aborrece la luz, y no viene a la luz,
para que sus obras no sean reprobadas.`"^
footnote:[Juan 3:19-21]
En otra parte Él nos dice: "`Y cuando Él +++[+++el Espíritu de Verdad]
venga, redargüirá al mundo de pecado, y de justicia, y de juicio.`"^
footnote:[Juan 16:8 RVG]
Pablo escribe a Tito:
"`Porque la gracia de Dios que trae salvación se ha manifestado a todos los hombres,
enseñándonos que, renunciando a la impiedad y a las concupiscencias mundanas,
vivamos en este presente mundo, sobria, justa y piadosamente.`"^
footnote:[Titus 2:11-12 RVG]
El autor de Hebreos habla de la "`Palabra viva y eficaz,`" que
"`discierne los pensamientos y las intenciones del corazón.`"^
footnote:[Hebreos 4:12]
Aquí tenemos varias Escrituras (entre muchas otras que podrían
ser citadas) que claramente testifican de que es la luz,
el Espíritu o la gracia de Jesucristo lo que reprende o convence en lo
secreto del corazón. ¿Dónde están las Escrituras que enseñan que estas
convicciones proceden de la conciencia natural del hombre caído?

No es la conciencia misma, _sino la Luz de Cristo que resplandece en la conciencia,_
la que hace que el hombre vea y sienta lo que es contrario a su Creador.
La conciencia es un don real y maravilloso de Dios;
pero sin la Luz de Cristo resplandeciendo en su interior, es como una linterna sin llama,
o una lámpara sin bombilla.

En todo lo que se ha dicho, el punto principal que deseo comunicar es este:
es porque no nos volvemos a estas reprensiones tan repetidas,
no amamos ni abrazamos la aparición interior de Cristo,
no sometemos nuestros corazones a Su luz y la tomamos como nuestra guía y maestra;
es porque buscamos excusas para el mal y para seguir nuestra propia voluntad;
es porque nos justificamos contra nuestras propias
convicciones en tantas cosas "`pequeñas`" que apagan,
contristan y resisten el Espíritu de santidad,
que experimentamos tan poco crecimiento en el poder del evangelio.

Estas no son "`pequeñeces,`" y nuestros intentos de rendirlas nos mostrarán
cuán grande es el lugar que ocupan en nuestro corazón. No hay tal cosa
como una "`cosa pequeña.`" Solo hay cosas de arriba y cosas de abajo.
Hay cosas que están en el Espíritu,
que son para el Espíritu y proceden del Espíritu de Dios,
y hay cosas que están en la carne, que son para la carne y proceden de la carne.
Y cuando el hombre se aferra a lo de abajo, cuando ama su propia vida más que la verdad,
su propia voluntad más que el camino de vida que son "`las reprensiones de la instrucción,`"^
footnote:[Proverbios 6:23 RVG]
cierra la puerta a los comienzos del poder de Dios.
Pisa el grano de mostaza justo cuando empieza a crecer.
Es fácil aplastar un roble cuando solo tiene cinco centímetros de altura.
Y muy a menudo sucede que, mientras esperamos algo grande e inconfundible,
algo impresionante y más conforme a nuestras propias expectativas,
"`menospreciamos el día de las pequeñeces,`"^
footnote:[Zacarías 4:10]
y perdemos la venida del poder del evangelio.

La razón principal por la que muchos permanecen extraños al poder transformador
de Dios es que sus corazones no se someten humilde y continuamente a las
primeras y más pequeñas manifestaciones de Su poder--la Luz de Jesucristo.
No se apartan fielmente del mal, ni rinden su voluntad al bien que ya son capaces de ver.
Y puesto que no son "`fieles en lo muy poco,`"^
footnote:[Lucas 19:17]
no crecen para experimentar más. En multitud de pequeñas maneras--pequeñas decisiones,
palabras y acciones a lo largo de cada día--contristan,
apagan y resisten los brotes del poder del evangelio en sus corazones.
Se familiarizan con la doctrina del evangelio, y sin embargo,
permanecen extraños a Su poder,
porque la "`obra eficaz`" del poder de Dios comienza
en el corazón con un silbo apacible que dice:
"`Volveos a mi reprensión: He aquí yo os derramaré mi espíritu,
y os haré saber mis palabras.`"^
footnote:[Proverbios 1:23]
